### ISSUE TITLE
pw: prefix verb corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#128]
Digitization errors were noticed while analyzing the records of pw.txt which
are identified as verbs with prefixes.

In general, the records are identified by the markup pattern in pw.txt of
```
<div n="p">— Mit {#PREFIX#}
EXAMPLE:
<div n="p">— Mit {#ava#}
```

Both types of errors are with the Sanskrit text identified above as PREFIX.

The first type, with roughly 500 instances, is a markup error, where the PREFIX 
includes not only the actual prefix, but also some example form. For instance:
```
old:  <div n="p">— Mit {#aBi , aByarCati#}
new: <div n="p">— Mit {#aBi#}, {#aByarCati#}
```
The second type, with roughly 100 instances, is due to a misspelling of the prefix.
For examples:
```
old: <div n="p">— Mit {#priti#}
new: <div n="p">— Mit {#prati#}
```
All these were checked against the scanned images, and were digitization errors (typos).

**Comment by drdhaval2785** [comment]
Hi Jim.
Just a github quirk.

If you write #128 in commit message, github would automatically show that 'this issue was referred in commit xxx'
