### ISSUE TITLE
ccs:2859, 2860, 2861, 2862

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#153]
date:	02/08/2020 10:14:04
dict:	ccs
Lnum:	2859, 2860, 2861, 2862
hw:	ālasya, ālāna, ālāpa, ālāpin
old:	ālasya n. Wassergt.  LB ālāna n. Trägheit.  LB ālāpa n. Pfahl zum Anbinden eines Elefanten.  LB ālāpin m. Rede, Gespräch; Gesang (der Vögel).
new:	ālasya n. Trägheit .  LB ālāna n. Pfahl zum Anbinden eines Elefanten.  LB ālāpa n. Rede, Gespräch; Gesang (der Vögel). LB ālāpin m. redend. 
comm:	Lots of Typos! LB There seems to be some mix up in a few lines. "ālasya" somehow got a translation fragment from the preceeding word. The correct translation  "Trägheit" is given to the following word ālāna (ID 2860). The translation for ālāna again is given in the following word "ālāpa",The following lemma ālāpin has now 2 entries (there should be only one) , the first (should be deleted) being the translation of "ālāpa", and the 2nd the correct one.

**Comment by gasyoun** [comment]
> Lots of Typos!

Too bad we do not know who committed such a good comment.

**Comment by funderburkjim** [comment]
Frank Ziesing noticed this. He also frequently submits corrections to PW .
