### ISSUE TITLE
Somehow missed correction

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#1615]
```
01/12/2024 22:02:24	MW	   210432	vraj	(Dhātup. viii, 79 )	 (Dhātup. vii, 79 )	  Typo - I believe this is a printing error at the top of the listing.	srhodes@snowcrest.net
```

**Comment by drdhaval2785** [comment]
Is vraj Dhatupatha viii,79 or vii,79? @Andhrabharati ?

**Comment by Andhrabharati** [comment]
It is vii,79 as per Westergaard's edition.

Pl. see the below--

![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/eb3f07e6-53ce-4edf-93a7-43bc037cbb5a)

and the last line of
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-westergaard/disp/index.php?section=7
