### ISSUE TITLE
'ks' in slp1 - which mostly should've been 'kz' or at times a typo/print error

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/csl-orig#1632]
It is stumbled upon while at pwk yesterday, and I've posted corrections in pwk and mw at [an issue there](https://github.com/sanskrit-lexicon/PWK/issues/106#issuecomment-1962293923).

As this appears to be present in (m)any other work(s), I am now looking at various repos of CDSL.

**1. The first one at ABCH**
![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/1ec959b5-88ac-4cb4-a928-6b5445cd2445)

Here it does not match the Chandas, with क्रव्यात्कर्बुरनैरृताक्सृक्पो, and should've been क्रव्यात्कर्बुरनैरृतावसृक्पो.
Though the verse has the error, the parsing has correctly derived नैरृत & असृक्प.

And, this reminds me of the ubiquitous parsing of Skt. plurals without the trailing long vowel and/or the visarga by many people; do we ever (on contrast) come across a plural word in English without the trailing 's'?

And, it is not out of context to cite the English-Sanskrit dictionaries (by Monier Williams, Borooah and Apte) which 'clearly' and 'properly' showed the pl. terminations of Skt. plurals, just like the English counterparts having s-termination.

**Does the present generation like to claim having a better knowledge of both the languages than these three persons?**

**Comment by Andhrabharati** [comment]
**2. Five in SKD** (with corrections marked)
[ks in SKD.txt](https://github.com/sanskrit-lexicon/csl-orig/files/14395495/ks.in.SKD.txt)

**Comment by Andhrabharati** [comment]
**3. 21 in VCP** (with corrections marked)
[ks in VCP.txt](https://github.com/sanskrit-lexicon/csl-orig/files/14395630/ks.in.VCP.txt)

**Comment by Andhrabharati** [comment]
**4. 2 in KRM** (with corrections marked)
[ks in KRM.txt](https://github.com/sanskrit-lexicon/csl-orig/files/14395921/ks.in.KRM.txt)

**Comment by Andhrabharati** [comment]
**5. 15 in MW** (with corrections marked)
[ks in MW.txt](https://github.com/sanskrit-lexicon/csl-orig/files/14395996/ks.in.MW.txt)

**Comment by Andhrabharati** [comment]
**6. one in WIL**

{#nizvaksena#} in line 228670 to be corrected as {#vizvaksena#}.

**Comment by Andhrabharati** [comment]
**7. 6 in AP90**

`(89314): {#kAMks-a#} > {#kAMkz-a#}`
`(147375): {#paks-ac#} > {#pakz-ac#}`
`(184445): {#Biks-a#} > {#Bikz-a#}`
`(202301): {#rakzyate havirasmAt, raks-asun#} > {#rakzyate havirasmAt, rakz-asun#}`
`(206570): {#laks-ac#} > {#lakz-ac#}`
`(206786): {#laks-yat#} > {#lakz-yat#}`

**Comment by Andhrabharati** [comment]
**8. 3 in CAE**

`(43013): {#°ksya#} > {#°kzya#}`
`(46076): {#cAracaksus#} > {#cAracakzus#}`
`(60432): {#divasa°ksaya#} > {#divasa°kzaya#}`

**Comment by Andhrabharati** [comment]
**9. One in CCS**

`(110967): {#Si/ksati#} > {#Si/kzati#}`

**Comment by Andhrabharati** [comment]
I would like to exclude the remaining PWG, to cover elsewhere **(if such a time ever comes)**, to be handled in a similar fashion as the **present pwk exercise** that @funderburkjim is undertaking.

This finishes the lookout that I had started as mentioned in the beginning of the issue.

And, hope this gets the attention of @drdhaval2785 sometime sooner.

**Comment by drdhaval2785** [comment]
Corrections made. Pending to install at server.
