### ISSUE TITLE
MW: adas

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#1635]
@aumsanskrit  submitted this correction to @funderburkjim by email.

> Please see the attached JPG for the Headword "adas". In my opinion 
the definitions listed on page 18 should be listed one after 
another, and the additional definition from page 1310 should be 
listed underneath. This perhaps would also require shifting the ID 
numbers slightly. This adjustment would better reflect the 
arrangement of the printed text.

![adas](https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/490ce6d8-8ddb-4868-a03b-0a3145c26a58)

**Comment by funderburkjim** [comment]
Agree with @aumsanskrit .
Will move the supplement entry L=3654.01 to 3654.11.  
That should give the desired result.

**Comment by funderburkjim** [comment]
After the change:

<img width="370" alt="image" src="https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/f3f5b3a1-4e74-4916-99f9-f471627458df">

**Comment by Andhrabharati** [comment]
@funderburkjim ,

See the annexure (1310,1) content--
![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/e891cfea-d727-42c1-9e19-329c3678c29e)

and the main text (18,1)--
![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/205e06d8-610c-4080-9972-779d288af0cc)

The accent mark in the annexure data clearly indicates that it has to be added to the (**adás**) nom. portion; and, not to the (**adas**) ind. portion.

As such, I propose that the change is to be reverted.

@aumsanskrit ,
I have noticed that most of your data doesn't contain the accent marks (probably, you are using the default option of "no accents").

**Comment by Andhrabharati** [comment]
@funderburkjim 

This is awaiting for you to correct.

**Comment by aumsanskrit** [comment]
The following consideration may be the general rule:  a supplemental entry (regardless of accent) does not take precedence over a Main Entry in MW dictionary.
