### ISSUE TITLE
gra:áṇu

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#1652]
date:	02/08/2024 21:31:07
dict:	gra
Lnum:	áṇu
hw:	11011
old:	anu, [Correction: áṇu,] 
new:	No 'correction' needed, read “áṇu”, as that is what correctly stands in Graßmann
comm:	??

**Comment by funderburkjim** [comment]
<img width="407" alt="image" src="https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/5028cd39-490e-489e-8857-3e1bb57541d8">

<img width="395" alt="image" src="https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/51170c0c-8b6e-4a1e-a2bf-aa2aecfe64ab">

<img width="293" alt="image" src="https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/309c3b43-584e-4f95-ac81-0ffd1a28e7fe">

**no change**

The cdsl seems right to me.   Perhaps Patrick is using a later edition of Grassman,
   where the accent is present?

**Comment by funderburkjim** [comment]
Patrick Stiles made this further comment:


`This was corrected by Graßmann on page 1741 (3. unveränderte  Auflage). `


@Andhrabharati  Can you provide an image of page 1741 of 3rd edition?

**Comment by Andhrabharati** [comment]
There is no VN portion in the revised ed. (1996) of GRA.

It incorporated all the GRA_VN matter in the main pages themselves, along with addl. corrections from few other sources. As such it ends with p.1740 of the org. edition.

And here is the rev. ed. p. 26 with the (orig.) GRA-VN correction incorporated--
![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/e4bde1fb-f1d5-48aa-bf52-fac2fe7bca0b)

**Comment by Andhrabharati** [comment]
![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/85d3d314-38ff-4263-a1c4-18df8e20409f)

**Why is "a." not underlined (as an abbr.) here?**

I see that the text file entry is duly marked it thus.

**Comment by Andhrabharati** [comment]
Probably the CR issue might've stopped @maltenth to take up the 1996 ed. of GRA for digitization.

But I've been wondering why he had chosen the 2nd ed.s of BOP (1867) and WIL (1874), while the 3rd ed. of those got published and were out of copy-right.

**Comment by funderburkjim** [comment]
## final
I think that the problem that Patrick identified was that CDSL had 'anu' (unaccented) instead of 'aṇu'  (also unaccented).  After correction, 

<img width="515" alt="image" src="https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/82f1f39b-9596-4ece-8e5c-57d2cc48bf26">
