### ISSUE TITLE
vcp: 17852, etc. verb spelling corrections

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#166]
In comparing vcp root spellings to MW, the following VCP spellings were thought to be in error.
```
17852 gUrha -> gUrdda   (print error?)
18633 GagDa -> GagGa (print error or typo?)
18794 GiRa -> GiRRa typo
37140 BrASaM -> BrASa  M is probably a typo, due to scan smudge.
38750 mrA -> mnA
48322 hrama -> hrasa   typo.
```

@drdhaval2785  Would you check these?
Details are in following comments.

**Comment by funderburkjim** [comment]
## 17852 gUrha -> gUrdda   
After change:
```
<L>17852<pc>2630,a<k1>gUrdda<k2>gUrdda
gUrdda¦ stutO saka0 cu0 uBa0 sew . gUrddayati te ajugUrddat ta .
<>“gUrddayatiH stutikarmmA” niGa0 “taM gUrdaya svarRaram” f0
<>7 . 19 . 1 “gUrdaya stuhi” BA0 krIqArTe gurddavat .
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75098921-ce67a180-5589-11ea-835c-027224e2315a.png)

**Comment by funderburkjim** [comment]
## 18633 GagDa -> GagGa
After change:
```
<L>18633<pc>2778,a<k1>GagGa<k2>GagGa
GagGa¦ hasane BvA0 para0 aka0 sew . GagGati aGagGIt . jaGagGa .
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75098952-0d95f280-558a-11ea-8d95-92d67faeeb88.png)

**Comment by funderburkjim** [comment]
## 18794 GiRa -> GiRRa
After change:
```
<L>18794<pc>2795,b<k1>GiRRa<k2>GiRRa
GiRRa¦ grahaRe BvA0 A0 saka0 sew idit . GiRRate aGismizwa
<>jiviRRe .
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75098961-3fa75480-558a-11ea-879a-e40e3cc17be3.png)

**Comment by funderburkjim** [comment]
## 37140 BrASaM -> BrASa
After change:
```
<L>37140<pc>4710,b<k1>BrASa<k2>BrASa
BrASa¦ BAse BvA0 A0 aka0 sew . BrASate BrASyate aBrASizwa .
<>PaRA0 BreSe baBrASe . fdit caNi na hrasvaH . dvit
<>aTuH BrASaTuH .
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75098983-7ed5a580-558a-11ea-8b22-5203f670f541.png)

**Comment by funderburkjim** [comment]
## 38750 mrA -> mnA
After change:
```
<L>38750<pc>4766,b<k1>mnA<k2>mnA
mnA¦ aByAse BvA0 para0 saka0 sew . manati amnAsIt mamnO .
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/75099002-b2b0cb00-558a-11ea-90fe-5d486b0c32ec.png)

**Comment by funderburkjim** [comment]
## 48322 hrama -> hrasa
After change:
```
<L>48322<pc>5440,a<k1>hrasa<k2>hrasa
hrasa¦ rave BvA0 pa0 saka0 sew . hrasati ahrasIt ahrAsIta
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/75099021-ea1f7780-558a-11ea-9203-6230a869c359.png)

**Comment by drdhaval2785** [comment]
All suggested corrections are OK.

An additional correction in GiRRa.

aGismizwa -> aGiRRizwa / aGiRizwa . I am not able to make out a small diagonal cut which differentiates RR from R.

**Comment by funderburkjim** [comment]
made `aGiRRizwa ` change.

Thanks for checking!

**Comment by gasyoun** [comment]
> All suggested corrections are OK.

Thanks.

> Thanks for checking!

Thanks for the catch!
