### ISSUE TITLE
skd: 24660, etc. spelling changes

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#169]
Several spelling changes made in process of analyzing skd verbs.

## 24660 and 24661: Ba -> Baqa 

Digitization after change:
```
<L>24660<pc>3-478<k1>Baqa<k2>Baqa
Baqa¦ ik Sive . iti kavikalpadrumaH .. (curA0-
<>para0-aka0-sew . idit .) SivaM kalyARa-
<>kriyA vedezveva . pratAraRe prasidDo'yam . ik
<>BaRqayati pratArako mugDaM DanadAnANgIkAreRa .
<>iti durgAdAsaH ..
<LEND>
<L>24661<pc>3-478<k1>Baqa<k2>Baqa
Baqa¦ i Na vAci . iti kavikalpadrumaH .. (BvA0-
<>Atma0-saka0-sew .) pariBAzaRa iti govinda-
<>BawwaH . parihAsa iti caturBujaH . i BaRqyate Na
<>BaRqate ziqgIM lokaH . iti durgAdAsaH ..
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75195023-2c7dbb80-5727-11ea-94e5-a62c3548cd7e.png)

**Comment by funderburkjim** [comment]
## 25518 BnASa -> BrASa, 25520 BnAsa -> BrAsa
Also some changes (Bn->Br) in 25519

Digitization after changes:```
```
<L>25518<pc>3-556<k1>BrASa<k2>BrASa
BrASa¦, ya Na BAsi . iti kavikalpadrumaH .. (divA0
<>Atma0-aka0-sew .) ya Na BrASyate . iti
<>durgAdAsaH ..
<LEND>
<L>25519<pc>3-556<k1>BrAsa<k2>BrAsa
BrAsa¦, f Ra Na wu BAsi . iti kavikalpadrumaH ..
<>(BvA0-Atma0-aka0-sew0 .) f avaBrAsat .
<>Ra Brese vaBrAse . Na BrAsate . wu BrAsaTuH . iti
<>durgAdAsaH ..
<LEND>
<L>25520<pc>3-556<k1>BrAsa<k2>BrAsa
BrAsa¦, ya Na BAsi . iti kavikalpadrumaH .. (divA0-
<>Atma0-aka-0sew .) ya Na BrASyate . iti
<>durgAdAsaH ..
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75195350-c0e81e00-5727-11ea-81f0-f7508724a2dd.png)

**Comment by funderburkjim** [comment]
## 34615 vuqa -> vruqa

Digitization after change:
```
<L>34615<pc>4-565<k1>vruqa<k2>vruqa
vruqa¦, Si saMvftisaMhatyoH . majje . iti kavikalpa-
<>drumaH .. (tudA0-kuwA0-para0-saka0-akaYca-sew .)
<>rePayuktaH . Si, vruqati avruqIt vuvroqa .
<>majjo majjanam . iti durgAdAsaH ..
<LEND>
```
Probably due to poor print quality.  Not calling this a 'print change'.

![image](https://user-images.githubusercontent.com/6393033/75195558-26d4a580-5728-11ea-8cba-a70bd308a974.png)

**Comment by drdhaval2785** [comment]
> 34615 vuqa -> vruqa

Fine.

Rest you have ventured into deep trouble.
Actual headwords are Baqaik, BaqaiNa, BrAsayaNa etc. How we want to handle it is a debatable point. Spell changes are OK. This needs a separate handling. Because ik, iNa etc are 'it' markers of Vopadeva's mugdhabodha grammer.

**Comment by gasyoun** [comment]
> 'it' markers of Vopadeva's mugdhabodha grammer.

And that Vopadeva sure was a strange fellow. He reinvented the whole grammar terminology again.

**Comment by drdhaval2785** [comment]
And there have been enough strange people in India. Vopadeva and Hemachandra were influential post Panini grammarians with significant clout.

**Comment by Andhrabharati** [comment]
> Because ik, iNa etc are 'it' markers of Vopadeva's mugdhabodha grammer.

It is not just Vopadeva's grammar that has these terms; all the schools of Skt. grammar have these terms.

> And that Vopadeva sure was a strange fellow. He reinvented the whole grammar terminology again.

Dhaval's above statement has lead to this remark.

Vopadeva did not revent the whole terminology, but just changed PaNini's terms at some places, and added a few more for his "school".

Many of the Gram. schools did such additions and changes, as per the resp. proponent's mind & and the region's "local" usages.

**Comment by Andhrabharati** [comment]
@drdhaval2785 

> Actual headwords are Baqaik, BaqaiNa, BrAsayaNa etc.

Again this is an erratic proposal. **The HWs are just Baqa, Baqa, BrAsa only.**

The next letters/words ik, i Na, ya Na etc. come under the grammatical treatment of the roots, to define their word-forming categories (the classes and sub-classes as they are known).

> How we want to handle it is a debatable point.

They just could be put after the HW as another field, broadly termed as "vyutpatti" (having the derivation, composition, usage ref. information etc.) (the way I did in my parsing of the dictionaries- MW, AP, PWG, ...), mostly before the meaning portion.

**Comment by drdhaval2785** [comment]
On a second thought, I agree with @Andhrabharati that headwords are Baqa, BrAsa etc only. Nothing further remains in this issue. Closing.
