### ISSUE TITLE
skd: 24660, etc. print changes

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#170]
These spelling changes are considered print changes, and so will be added to [skd_printchange.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/skd/skd_printchange.txt).

## 36534 SraBa -> Srama 

digitization after change:
```
<L>36534<pc>5-154<k1>Srama<k2>Srama
Srama¦ u Ba ya Yi ir tapaHKedayoH . iti kavi-
<>kalpadrumaH .. (divA0-para0-aka0-sew . ktvAvew .)
<>u, SramitvA SrAntvA . Ba ya, SrAmyati lokaH
<>tapaH karoti Kidyati vetyarTaH . Yi, SrAnto-
<>'sti . ir aSramat aSrIt . asmAt puzA-
<>ditvAnnityaM Na ityanye . DUryyAn viSrAmayeti sa
<>iti raGO SrAma t ka mantre ityadantasya rUpam .
<>iti durgAdAsaH ..
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75196034-21c42600-5729-11ea-8d93-d677727ddd13.png)

**Comment by funderburkjim** [comment]
## 37043 za -> zU

Digitization after change:
```
<L>37043<pc>5-194<k1>zU<k2>zU
zU¦, Na la sUtO . iti kavikalpadrumaH .. (adA0
<>Atma0-saka0-aniw .) mUrdDanyAdiH . Nala,
<>sUte . iti durgAdAsaH ..
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75196153-651e9480-5729-11ea-8c60-af5d8581964b.png)

**Comment by funderburkjim** [comment]
## 37112 zRuma -> zRusa

Digitization after change:
```
<L>37112<pc>5-198<k1>zRusa<k2>zRusa
zRusa¦, ya Bakze . iti kavikalpadrumaH .. (divA0
<>para0-saka0-sew .) dantyanakArayuktaH . ya,
<>snusyati suzRoma . iti durgAdAsaH ..
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/75196301-b3339800-5729-11ea-9599-b8ebdedf93ad.png)

**Comment by funderburkjim** [comment]
@drdhaval2785   Request you check these changes , and those of #169

**Comment by drdhaval2785** [comment]
OK. see #174 for verbs of SKD.
