### ISSUE TITLE
mw: 40722, olaj etc. Mark as verbs

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#171]
Several entries are added to those marked as verbs in MW.

## 40722 olaj and 40723 olj

Also added `[<s>olaRq</s>]`  to the text.

Digitization after change:
```
<L>40722<pc>236,1<k1>olaj<k2>olaj<e>2
<s>olaj</s> ¦ <ab>vv.ll.</ab> for the above. [<s>olaRq</s>] <info verb="root"/>
<LEND>
<L>40723<pc>236,1<k1>olj<k2>olj<e>2
<s>olj</s> ¦ <ab>vv.ll.</ab> for the above. [<s>olaRq</s>] <info verb="root"/>
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75197688-df044d00-572c-11ea-9f61-9c2cec08a641.png)

**Comment by funderburkjim** [comment]
## 241374 sAt

Digitization after change:
```
<L>241374<pc>1200,1<k1>sAt<k2>sAt<h>2<e>1
<hom>2.</hom> <s>sAt</s> ¦ a <s1 slp1="sOtra">Sautra</s1> root meaning ‘to give pleasure’ <ls>Pāṇ.</ls>; <ls>Vop.</ls> <info verb="root"/>
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75198019-a7e26b80-572d-11ea-8c09-b791a597698a.png)

**Comment by funderburkjim** [comment]
## 44620 kark

Digitization after change:
```
<LEND>
<L>44620<pc>255,3<k1>kark<k2>kark<e>1
<s>kark</s> ¦ (a <s1 slp1="sOtra">Sautra</s1> root), to laugh.<info verb="root"/>
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/75198256-2a6b2b00-572e-11ea-8e7b-279548f86769.png)

**Comment by funderburkjim** [comment]
## 51978, kut

```
<L>51978<pc>290,1<k1>kut<k2>kut<e>1
<s>kut</s> ¦ a <s1 slp1="sOtra">Sautra</s1> root (<ab>i.e.</ab> one found in grammatical <s1 slp1="sUtra">Sūtra</s1>s only), to spread.<info verb="root"/>
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75198392-7c13b580-572e-11ea-8d5d-2ca66919ee8f.png)

**Comment by funderburkjim** [comment]
## 244005, sik

```
<L>244005<pc>1213,3<k1>sik<k2>sik<e>1
<s>sik</s> ¦ a <s1 slp1="sOtra">Sautra</s1> root meaning ‘to scatter about, sprinkle’ (<ab>cf.</ab> √ <s>sic</s>, <s>sIk</s>). <info verb="root"/>
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75198559-efb5c280-572e-11ea-9d26-9e7a1e81f886.png)

**Comment by funderburkjim** [comment]
## 247217, sund

```
<L>247217<pc>1227,1<k1>sund<k2>sund<e>1
<s>sund</s> ¦ a <s1 slp1="sOtra">Sautra</s1> root meaning ‘to shine, be bright’ <ls>Vop.</ls><info verb="root"/>
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/75198678-32779a80-572f-11ea-88c6-550de1388129.png)

**Comment by funderburkjim** [comment]
## 259867, svUrC

```
<L>259867<pc>1285,1<k1>svUrC<k2>svUrC<e>1
<s>svUrC</s> ¦ See √ <s>sPUrC</s>.<info verb="root"/>
<LEND>
```
![image](https://user-images.githubusercontent.com/6393033/75198928-cd707480-572f-11ea-8508-db1998034a39.png)

and here is 'sPUrC'
```
<L>257027<pc>1271,2<k1>sPUrC<k2>sPUrC<e>1
<s>sPUrC</s> ¦ (also written <s>svUrC</s>) <ab>cl.</ab> 1. <ab>P.</ab> <s>sPUrCati</s>, to spread, extend, <ls>Dhātup. vii, 33</ls>;
<div n="to"/>to forget, <ls>ib.</ls><info westergaard="sPurCA,7.33,01.0131"/><info verb="root" cp="1P"/>
<LEND>
```

**Comment by funderburkjim** [comment]
## 220057 SU

```
<L>220057<pc>1085,1<k1>SU<k2>SU<h>1<e>1
<hom>1.</hom> <s>SU</s> ¦ a weak form of √ <s>Svi</s> <ab>q.v.</ab><info verb="root"/>
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/75199439-1b39ac80-5731-11ea-8605-9935df7a8132.png)

**Comment by gasyoun** [comment]
Such a catch! I'm in debt before Jim.
