### ISSUE TITLE
VCP: questionable upasarga patterns

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#180]
There are several odd upasarga patterns in VCP, as shown below.

Perhaps others will notice some additional typographical errors, or can confirm the correctness
of the digitization.

## Avis + prAdus = AvisprAdus
headword 'BU', page 4678
```
<HI>anu--anuBave jYAnaBede saka0 anuBavaSabde dfSyam .
<HI>antar + tiroBAve aka0 .
<HI>aBi + tiraskAre saka0 . aBiBavati SatrUn .
<HI>Avis + prAdus + praTamaprakASe .   <<<
<HI>ud--utpattO aka0 .
<HI>tiras antarDAne sTitasya vastunaH kAraRAtmanA'vasTAne aka0
<HI>parA + asahane parABavaH .
<HI>pari + tiraskAre pariBavati atikramya Bavane .
```

![image](https://user-images.githubusercontent.com/6393033/75617440-0c863780-5b2d-11ea-9234-752978361871.png)

**Comment by funderburkjim** [comment]
## trad

root DA, Page3869-a

```
<HI>prati + vi + pratirUpAcaraRe “kzipramasminnaravyAGra cAraH prati-
<>viDIyatAm” rAmA0 sunda0 pratIkAre ca “kziprameva kasmAnna
<>prativihitamAryyeRa” mudrArA0 candraguptoktiH “na pAritaM
<>prativiDA tum” tatrEva cARakyoktiH .
<HI>trad + Adare viSvAse ca . “SraddaDAti ka iveha na sAkzAt” nEza0 .
<HI>sam + samyagviDAne yojane SlezaRe aBisanDO . “manasyetAni
<>sanGAya manasA sampraDArayet” BA0 ASva0 42 a0 .
```

![image](https://user-images.githubusercontent.com/6393033/75617469-90d8ba80-5b2d-11ea-8975-04b8ceb983e8.png)

**Comment by funderburkjim** [comment]
## uda + graha -> ud

root graha, Page2744a

```
<HI>ud + UrdDvaM vigfjya dAne “vAjasya mA prasava udgrABeRoda
<>graBIt” yaju017 . 63 . UrdDaM vigfjya dAmam udgrahaH”
<>vedadI0 “udgfhRate svAhodgfhItAya svAhA” 22 . 26 .
<>udDftya uttolya grahaRe “SaktiM yo'gryAmudagrahIt” BawwiH .
<HI>uda + graha + Ric . udgrAhi--upanyAse “udgrAhitamu-   <<<
<>panyastam” vEjayantI “viSezaviduzaH SAstraM yattavodgrA-
<>hyate mayA” mAGaH . “mojjigrahaH sunItAni” BawwiH
<HI>upa + ud + jYAne . “tasya hi muKamupodgfhRannuvAca” CA0 u0
```

![image](https://user-images.githubusercontent.com/6393033/75617505-0a70a880-5b2e-11ea-9068-eef7e2c76ac7.png)

**Comment by funderburkjim** [comment]
## nis + nir = nir

Why repetition of upasarga?
Usually, this would be interepreted as 'nirnir',  but I interpreted as just 'nir'.
5 cases, under roots Ikza, kasa, kfza, Kana, jYA.
Details under Ikza, Page1007-a
```
<HI>sam + upa + samyagupekzAyAm . “SatrupakzaM samADAtu yomo-
<>hAt samupekzate” BA0 sa0 1060 Slo0 .
<HI>nis + nir + niHSezeRa darSane niScayArTaM darSane ca . “yAvadetA-
<>nnirIkze'haM yodDukAmAnavasTitAn” gItA .
<HI>pari + tattvAnusanDAne pramARAdyupanyAsena vastutattvAvaDAraRe ca
<>“parIkzya lokAn karmmacitAn” SrutiH . nyAyasUtravfttyAdO
```

![image](https://user-images.githubusercontent.com/6393033/75617595-36405e00-5b2f-11ea-8c5f-99cdedf2e346.png)

**Comment by drdhaval2785** [comment]
1. Avis and prAdus are two separate preverbs.
AvirBAva and prAdurBAva mean the same thing. So maybe we should split them into two entries.
2. It is 'Srad' - SradDA
3. uda to 'ud' is OK
4. Just like 1. The author seems to club two upasargas in a single entry if the meaning is the same.

**Comment by gasyoun** [comment]
> AvirBAva and prAdurBAva mean the same thing. So maybe we should split them into two entries.

Makes sense.

**Comment by funderburkjim** [comment]
Changes 'trad' to 'Srad' -- consider a typo.

Treated `Avis + prAdus` as if just 'Avis'.   Do not feel confident to change
the digitization to two entries.

@drdhaval2785   Thanks for help.
