### ISSUE TITLE
skd: 35999, SucaH -> Suca

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#186]
This appears to be a print error. 
The print clearly shows the visarga:
![image](https://user-images.githubusercontent.com/6393033/75740420-94a74100-5cd5-11ea-960f-31ba4909192e.png)

But that first entry is also clearly a verb.  (There is also a second verb entry).

AFAIK,  there are no other verb entries in  skd (or kavikalpadruma) whose spelling ends with 
visarga.

Thus, it seems reasonable to remove that visarga, and to classify as print change.

**Comment by drdhaval2785** [comment]
Print change for sure.
