### ISSUE TITLE
PWG: 114357, sparS

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#189]
patyupa -> pratyupa  (print change):

https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=PWG&page=7-1362

![image](https://user-images.githubusercontent.com/6393033/76119762-180ab000-5fbe-11ea-82d9-eb2f3ef5de4f.png)

**Comment by gasyoun** [comment]
2020 gives lots of fruits.
