### ISSUE TITLE
MW: 140875, pruzwA

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#190]
This is a question.  

Here is current digitization:
```
<L>140875<pc>711,3<k1>pruzwA<k2>pruzwA<e>2
<s>pruzwA</s> ¦ <ls>Pāṇ. 3-1, 17</ls>, <ab>Vārtt.</ab> 1.
<LEND>
<L>140876<pc>711,3<k1>pruzwAyate<k2>pruzwAyate<e>3
<s>pruz°wAyate</s> ¦ <ls>Pāṇ. 3-1, 17</ls>, <ab>Vārtt.</ab> 1.<info verb="root"/>
<LEND>
```

![image](https://user-images.githubusercontent.com/6393033/76151177-11447180-6080-11ea-86e3-119f36928d13.png)

I could not find the reference (pruz is not mentioned in Pan 3.1.17).

Is 'pruzwA' a noun ('pruz + tA' = wetness?) ,   and an (un-named) verb created from it with 3s = pruzwAyate?

Or, should 'pruzwA' be considered a (denominative) verb, with 3s = pruzwAyate ?

Or, what ?

**Comment by funderburkjim** [comment]
Here is the corresponding entry (headword 'pruzwAy') in pw:

![image](https://user-images.githubusercontent.com/6393033/76151247-e3136180-6080-11ea-803a-0b28837a3fb9.png)

**Comment by drdhaval2785** [comment]
The following is the sought after vArttika.
```
अटाट्टाशीकाकोटापोटासोटाप्रुष्टाप्लुष्टाग्रहणं कर्तव्यम्। अटायते। अट्टायते। शीकायते। कोटायते। पोटायते। सोटायते। प्रुष्टायते। प्लुष्टायते।
```

This vArttika enumerates the verbs missed out by Panini. This includes pruzwAyate.
