### ISSUE TITLE
ap90: 7387, inv Period after P,U,A

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#195]
In ap90,  most verbs may be identified by a class-pada coding. Such as
`{#in#}¦ 6. 8. P. Ved. {@1@} To go.`   Note the period after the P:  `P.`
![image](https://user-images.githubusercontent.com/6393033/76561785-61ee0d00-647a-11ea-8f14-93d4c8c4dd16.png)

However, in a few cases this period is missing. For instance:
`{#inv#}¦ 6 P {@1@} To go. `
![image](https://user-images.githubusercontent.com/6393033/76561910-a4afe500-647a-11ea-8fbe-25bb7aa36664.png)

There are roughly 3000+ cases WITH PERIOD, and a small number (see instances below) without the period.   

It seems reasonable to impose a small consistency in the digitization, by introducing the periods: e.g. `{#inv#}¦ 6. P. {@1@} To go. `

This will be documented as a print change.

~~Notice also a period was put after the '6' in the 'inv' example, again for consistency.~~

It was found that in 3000+ cases, there is NO period after the conjugation class.
And in 300+ cases, there IS a period after the conjugation class.  
Thus, for now, I'm not going to either insert or remove periods after the conjugation class number.

The records changed will be noted in other comments below.

**Comment by funderburkjim** [comment]
## Front matter verb comment
Note that the above observation is consistent with Apte's intent as expressed in the front matter.

```
11. (a). In the case of verbs, the Arabic figure before P., A. and U. denotes the conjugation
to which the root belongs; P. denoting Parasmaipada, A. Atmanepada, and U. Ubhayapada (P. and A.).

Den. stands for Denominative, and here the 3rd pers. sing. present tense is given throughout.

(b). Under each root the 3rd person singular present tense and of the Perfect, Aorist, two Futures
and Infinitive in the case of important roots, and the past passive participle wherever noteworthy, are given
throughout. The forms of the Passive, Causal and Desiderative, wherever noteworthy, are given after them,
or after the senses of the primitive base, where there is any peculiarity in their senses.

(c). Verbs formed by prefixing prepositions to roots are given separately in their own alphabetical
order, except in cases where there are no derivatives from such verbs.

(d). Roots sometimes change their form or pada (voice) or both, when used in particular senses,
or when preceded by particular prepositions. Such changes are denoted within brackets.

(e). When a root belongs to different conjugations with different meanings, Roman figures are used
to mark this difference, (cf. अस्, गुप्, हा &c.), the root being repeated only once.
```

**Comment by funderburkjim** [comment]
## First batch: periods added
```
matches for " [UP] " in buffer: ap90.txt
  64006:{#inv#}¦ 6 P {@1@} To go. {@--2@} To per-
 125377:<>browsed &c. --II 1 P, 10 U ({#daMSati,#}
 144843:{#nizpU#}¦ 9 U {@1@} To purify. {@--2@} To
 149105:{#patIyati#}¦ Den. P To wish for a
 152475:{#paripA#}¦ I. 1 P To drink; {#upani-#}
 154908:{#parvatIkf#}¦ 8 U To make into a moun-
 166460:{#pratinaMd#}¦ 1 P {@1@} To bless; {#tO gu-#}
  198828:<>worship, adore. --II. 1 P ({#yakzati#})
 201294:<>--II. 1. P., 10 U ({#yIjati, yojayati-te#}) To
 223420:{#vivfj#}¦ 10 U or {%Caus.%} {@1@} To shun,
 254655:{#suww#}¦ 10 U ({#suwwayati-te#}) {@1@} To des-
 258049:{#sten#}¦ 10 U (Strictly a denom.
```

## non-padas, still missing period

`144840:<>{#jo nu sekaH#} U 3. 11.  `
U. = Uttararāmacarita   (literary source).  1300+ instances.

### Not a 'pada' but literary source 
K. P.   == Kāvyaprakāśa.    (300+ instances).  In next, the period is missing after P
`188478:<>{#ho viBramayati#} K. P. 10; so {#ESvaryaº,#}    `

**Comment by funderburkjim** [comment]
## Second batch
Looking for U,P, or A preceded by space and followed by comma.  A period is inserted.
Example:
`{#anupA#}¦ 2 P, {#--pAl#} 10 P. {@1@} To` -> 
`{#anupA#}¦ 2 P., {#--pAl#} 10 P. {@1@} To`

![image](https://user-images.githubusercontent.com/6393033/76565383-d5931880-6480-11ea-950b-88d54b3c43ef.png)

As indicated below, several matching patterns do not need a period.
```
21 matches for " [UPA], " in buffer: ap90.txt
  17240:{#anupA#}¦ 2 P, {#--pAl#} 10 P. {@1@} To
  17952:{#anumA#}¦ 3 A, 2 P. {@1@} To infer, (as
  23576:<>ed to {#apaskf#} A, in this sense {#apAcca-#}
  50907:{#Akf#}¦ 8 U, 5 P. {@1@} To bring near
  53482:{#Atura#}¦ {%a.%} [{#IzadarTe A, at-urac#}]    <<< Not changed
  83337:<>labial letter; {%i. e.%} {#u, U, p, P, b, B,#}   <<< Not changed
  84995:<>ter; namely {#a, A, k, K, g, G, N#} and   <<< Not changed
 103925:{#gA#}¦ 1 or 2 A, 3 P. ({#gAte, jigAti#})
 108858:<>like {#ava, A, upa, vi, saM#} &c. are added      <<< Not changed
 130668:<>(With prepositions like {#ava, A, pra,#}      <<< Not changed
 152848:{#pariBraMS#}¦ 1 A, 4 P. {@1@} To fall or
 155298:{#pavitrayati#}¦ Den. P, To purify,
 179520:{#bahulIBU#}¦ 1 P, {@1@} To spread, increase,
 203303:<>preceded by {#vi, A, pari#} and {#upa; reme,#}
 205159:{#rizaRyati#}¦ Den. P, Ved. {@1@} To in-
 224214:<>{#viSvaM pAlyaM#} U, 3. 30; {#viSvasminnaDunAnyaH#}    <<< Lit src.  U. 3. 30
 239770:<>{#A, I, U, E,#} and {#O#}. {#--durgaM (zaqdurgaM)#} the  <<< Not changed
 242737:{#saMkzuB#}¦ 1 A, 4. 9. P. To tremble,
 246857:<>{#kzaraM#} N. of the vowels {#a, A, i, I, u,#}     <<< Not changed
 264090:{#hu#}¦ 3 P, ({#juhoti, huta;#} {%pass.%} {#hUyate;#} {%caus.%}
 265293:<>{#f,#} and {#x#} short; and {#A, I, U, f, e, E, o,#} and   <<< Not changed
```

**Comment by funderburkjim** [comment]
## misc. other patterns
A period also was added after these pada references:
```
{#ak#}¦ 1 P({#akati#}) To go, move
{#avaman#}¦ 4 A(or Poet. P.) {@1@} To
{#ir#}¦ 6 P({#irati#}) To go.
{#kep#}¦ 1 A({#kepate#}) To shake or
{#Kur#}¦ 6 P({#Kurati#}) To scratch, cut,
{#galB#}¦ 1 A({#galBate, galBita#}) To be
{#glas#}¦ {@1@} A({#glasate, glasta#}) To eat,   <<< 1 A. (...)
{#cAy#}¦ 1 U({#cAyati-te#}) {@1@} To observe,
{#JF#}¦ 4. 9. P({#JIryati#} or {#JfRAti#}) To
{#nivid#}¦ 2 P(generally in the
{#niz#}¦ 1 A({#nezati#}) To moisten, wet.
{#nud#}¦ 6 U({#nudati-te, nutta#} or {#nunna, praRuda-#}
{#Barts#}¦ 10 A({#Bartsa yate;#} P. also some-
{#SviMd#}¦ 1 A({#SviMdate#}) To become
{#srek#}¦ 1. A({#srekate#}) To go, move.
```

**Comment by gasyoun** [comment]
> It was found that in 3000+ cases, there is NO period after the conjugation class.
> And in 300+ cases, there IS a period after the conjugation class.
> Thus, for now, I'm not going to either insert or remove periods after the conjugation class number.

So you added periods in just a small part of the findings after all?

**Comment by funderburkjim** [comment]
Right, just added periods after the pada (A,P,U).

**Comment by gasyoun** [comment]
So closable?

**Comment by funderburkjim** [comment]
yes. closing now.
