### ISSUE TITLE
ap90: 30769, stip, etc. Remove bold from conjugation class

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#196]
## 30769, stip

```
OLD:
{#stip#}¦ {@1@} A. ({#stepate#}) To ooze, drop,
NEW:
{#stip#}¦ 1 A. ({#stepate#}) To ooze, drop,
```
In the digitization, {@X@} means that 'X' is bold **X** in print.

![image](https://user-images.githubusercontent.com/6393033/76580836-b5c31b00-64a7-11ea-89d3-7dd9e1b7df09.png)

Based purely on physical appearance, it is often indefinite in  the printed text of ap90 whether a bit of text  bold face or normal face.

However, as the three examples illustrate,  there is a functional use of bold in Apte, namely to
distinguish sections with alternate definitions.   
Thus, in stip,  the '1' is not a section marker, since there is no 2nd section.  Thus, we conclude that '1' should not be bold; rather it is indicating first conjugation.
In stiG, similarly the '5' cannot be a section number, so should not be bold.  But the 1,2,3 are section numbers so should be bold.

While searching for verbs,  several cases were found where the class number was coded as Bold;
The changes made were to remove this bold markup.
All these were treated as print changes.

**Comment by funderburkjim** [comment]
## Details of changes
ap90: 
     2376,apaDvaMs  1 A -> 1 A. ;
     8579, upadaMs. {@1@} P. -> 1 P. ;
     9352, Unayati. Den P. -> Den. P. ;
     9590, elAyati.  Den P. -> Den. P. ;
     9923, kak. {@1@} A. -> 1 A. ;
    10302,kaMp. {@1@} A. -> 1 A. ;
    10988,kuk. {@1@} A. -> 1 A. ;
    11679,knUy. {@1@} A. -> 1 A. ;
    11782, kliMd. {@1@} U. -> 1 U. ;
    11794, klu. {@1@} A. -> 1 A. ;
    11795, kleS. {@1@} A. -> 1 A. ;
    12652, gUrd. {@1@} A. -> 1 A. ;
    12734, gozW. {@1@} A. -> 1 A. ;
    12838, glev. {@1@} A. -> 1 A. ;
    12839, glez. {@1@} A. -> 1 A. ;
    12987, cak. {@1@} U. -> 1 U. ;
    15133, dakz. {@1@} A. -> 1 A. ;
    15171, daD. {@1@} A. -> 1 A. ;
    15753, dyut. {@1@} A. -> 1 A. , dyetate -> dyotate ;
    16120, DUmAyati. Deu. -> Den.  print change ; 
    16335, naB. {@1@} A. -> 1 A. ;
    17641, paR. {@1@} A. -> 1 A. ;
    17798, parAkram. {@1@} U. -> 1 U. ;
    18262, pariSaMk. {@1@} A. -> 1 A. ;
    18305, parizvaMj. {@1@} A. -> 1 A. ;
    19489, prakawayati. Den P. -> Den. P. ;
    20643, pralaB. {@1@} A. -> 1 A. ;
    21034, prahlAd. {@1@} A. -> 1 A. ;
    21385, proT. {@1@} U. -> 1 U. ;
    21415, plakz. {@1@} U. -> 1 U. ;
    21814, buMd. {@1@} U. -> 1 U. ;
    22167, Bikz. {@1@} A. -> 1 A. ;
    22455, makk. {@1@} A. -> 1 A. ;
    22479, maMg. {@1@} U. -> 1 U. ;
    22673, maMd. {@1@} A. -> 1 A. ;
    23230, muKarayati.  Den, P. -> Den. P. ;
    23741, yAc. {@1@} A. -> 1 A. ;
    23836, yut. {@1@} A. -> 1 A. ;
    23948, raMG. {@1@} U. -> 1 U. ;
    24537, lasj. {@1@} A. -> 1 A. ;
    25103, varc. {@1@} A. -> 1 A. ;
    25725, vigah. {@1@} A. -> 1 A. ;
    26011, viDvaMs. {@1@} A. -> 1 A. ;
    26251, viBrAj. {@1@} A. -> 1 A. ;
    26466, vivad. {@1@} A. -> 1 A. ;
    26735, visraNs. {@1@} A. -> 1 A. ;
    27710, SalB. {@1@} A. -> 1 A. ;
    27863, SAl. {@1@} A. -> 1 A. ;
    28039, SIB. {@1@} A. -> 1 A. ;
    28106, SuB. {@1@} A. -> 1 A. ;
    28196, SfD. {@1@} A. -> 1 A. ;
    28344, SraMk. {@1@} A. -> 1 A. ;
    28548, zvakk. {@1@} A. -> 1 A. ;
    29627, saMpare. {@2@} A. -> 2 A. ;
    30769, stip. {@1@} A. -> 1 A. ;
  ```

## Three 'false positives'
In these cases, the context indicates that the bold '1' should be bold (and is hence not a class number)
```
   940,aDikram {@1@} U. 
     2224, anvAraB. {@1@} A.  
    25890, vitap. {@1@} A. 
```
For example aDikram.  There is a section 2, so the '1' must be a section number, not a conjugation class; hence it should indeed be bold.  
![image](https://user-images.githubusercontent.com/6393033/76581372-8c0af380-64a9-11ea-8f32-59702da6e3b0.png)

The other two are similar.

**Comment by funderburkjim** [comment]
## Three 'false positives'
In these cases, the context indicates that the bold '1' should be bold (and is hence not a class number)
```
   940,aDikram {@1@} U. 
     2224, anvAraB. {@1@} A.  
    25890, vitap. {@1@} A. 
```
For example aDikram.  There is a section 2, so the '1' must be a section number, not a conjugation class; hence it should indeed be bold.  
![image](https://user-images.githubusercontent.com/6393033/76581372-8c0af380-64a9-11ea-8f32-59702da6e3b0.png)

The other two are similar.

**Comment by gasyoun** [comment]
> There is a section 2, so the '1' must be a section number, not a conjugation class

So no class at all?

**Comment by funderburkjim** [comment]
In that example, yes, no class at all given in the text.

**Comment by gasyoun** [comment]
> In that example, yes, no class at all given in the text.

Is it not strange, that pada given, but not the class? It's like a defected documentation?

**Comment by funderburkjim** [comment]
## Some additional changes

These show the records that were changed, before the change.
Typically, the change was made to 'regularize' the format.  Sample changes
* '1 A' -> '1 A.'     (missing period)
* '2A.' -> '2 A.'     (missing space)

```
<L>19<pc>0002-c<k1>aMh<k2>aMh
{#aMh#}¦ 1 A {#aMhate, aMhituM#} To go; ap-
<>proach; set out, Bk. 3. 25, 46; 14. 51,

<L>1028<pc>0050-a<k1>aDiSI<k2>aDiSI
;{#aDiSI#}¦ 2A. To lie or sleep upon,

<L>1816<pc>0077-c<k1>anumf<k2>anumf
;{#anumf#}¦ 6A. To follow in death;

<L>1818<pc>0078-a<k1>anuyA<k2>anuyA
;{#anuyA#}¦ 2P. {@1@} To follow, go after

<L>2522<pc>0112-a<k1>apavf<k2>apavf
;{#apavf#}¦ 5U. To open, uncover, dis-

<L>4477<pc>0179-a<k1>avaci<k2>avaci
;{#avaci#}¦ 3P. {@1@} To worship, honour,

<L>4522<pc>0180-a<k1>avatan<k2>avatan
;{#avatan#}¦ 8U. {@1@} To stretch or ex-

<L>7969<pc>0299-c<k1>utsukAyate<k2>utsukAyate
;{#utsukAyate#}¦ Den. A To become uneasy

<L>8186<pc>0308-b<k1>udDA<k2>udDA
;{#udDA#}¦ I. 3P. Ved. {@1@} To abandon or

<L>12509<pc>0458-b<k1>gAh<k2>gAh
;{#gAh#}¦ {@1@} A [{#gAhate, jagAhe, agAhizwa,#}

<L>13004<pc>0481-b<k1>cakz<k2>cakz
;{#cakz#}¦ 2 A ({#cazwe#}) (Defective in
;<>non-conjugational tenses). {@1@} To

;{#Df#}¦ I. 6 A (Supposed by some to
;<>be a passive form of {#Df;#}{# (Driyate, Dfta)#}

<L>16607<pc>0618-a<k1>nikf<k2>nikf
;{#nikf#}¦ 8U. Ved. {@1@} To humiliate,

<L>18075<pc>0677-a<k1>paripA<k2>paripA
;{#paripA#}¦ I. 1 P To drink; {#upani-#}

<L>19848<pc>0736-c<k1>praticakz<k2>praticakz
;{#praticakz#}¦ 2 A {@1@} To see, perceive,

<L>20968<pc>0767-c<k1>prasPur<k2>prasPur
;{#prasPur#}¦ 6P. {@1@} To quiver, tremble.

<L>21605<pc>0790-a<k1>balAyate<k2>balAyate
;{#balAyate#}¦ Den. A To put forth strength

<L>21664<pc>0793-b<k1>bahulIBU<k2>bahulIBU
;{#bahulIBU#}¦ 1 P, {@1@} To spread, increase,

<L>21668<pc>0793-b<k1>bAq<k2>bAq
;{#bAq#}¦ 1 A ({#bAqate#}) {@1@} To bathe. {@--2@}

<L>22145<pc>0815-c<k1>BAz<k2>BAz
;{#BAz#}¦ {@1@} A ({#BAzate, BAzita#}) {@1@} To say

<L>24185<pc>0913-b<k1>rizaRyati<k2>rizaRyati
;{#rizaRyati#}¦ Den. P, Ved. {@1@} To injure

<L>26221<pc>0984-c<k1>viBAz<k2>viBAz
;{#viBAz#}¦ 1 A {@1@} To lay down as an optional rule.

<L>26790<pc>1003-c<k1>vIj<k2>vIj
;{#vIj#}¦ I. {@1@} A ({#vIjate#}) To go. --II.

<L>27242<pc>1018-b<k1>vyapatrap<k2>vyapatrap
;{#vyapatrap#}¦ 1 A {@1@} To turn away

<L>31170<pc>1161-c<k1>svask<k2>svask
;{#svask#}¦ 1 A ({#svaskate#}) See {#zvask#}.

<L>31624<pc>1177-c<k1>hlAd<k2>hlAd
;{#hlAd#}¦ 1 A ({#hlAdate, hlanna#} or {#hlAdita#}) {@1@}

```
