### ISSUE TITLE
why hwextra here

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#2]
Purpose of hwextra files is a way to get extra headwords for entries.

## acc example
acc_hwextra.txt has, as first line,
```
<L>12.1<k1>akzacaraRa<k2>akzacaraRa,<type>alt<LP>12<k1P>akzapAda
```
This means that `akzacaraRa` is an alternate headword for `akzapAda`.  

akzapAda has L=12.  
When we construct acchw.txt, we make use of alternate headwords:
```
<L>12<pc>1-001,1<k1>akzapAda<k2>akzapAda<ln1>39<ln2>42
<L>12.1<pc>1-001,1<k1>akzacaraRa<k2>akzacaraRa,<type>alt<LP>12<k1P>akzapAda<ln1>39<ln2>42
```

Then, when we construct acc.xml, we make use of acchw.txt and acc.txt. Results are:
```
<H1><h><key1>akzapAda</key1><key2>akzapAda</key2></h><body><s>akzapAda</s>  or <s>akzacaraRa,</s> a name of Gautama, the philo- <br/>sopher, Hall p. 20.</body><tail><L>12</L><pc>1-001,1</pc></tail></H1>
<H1><h><key1>akzacaraRa</key1><key2>akzacaraRa,</key2></h><body><alt><s>akzacaraRa</s> is an alternate of <s>akzapAda</s>.</alt> <s>akzapAda</s>  or <s>akzacaraRa,</s> a name of Gautama, the philo- <br/>sopher, Hall p. 20.</body><tail><L>12.1</L><pc>1-001,1</pc><hwtype n="alt" ref="12"/></tail></H1>
```

**Comment by funderburkjim** [comment]
## suggest leave in pywork

The example shows that only usage of hwextra is in making the list of headwords (acchw.txt);  then there are further uses indirectly when acchw.txt is used.

All this work is done in the pywork directory for a dictionary.

Thus, the csl-pywork directory would be a better place to put hwextra files.

@drdhaval2785 Agree?

**Comment by drdhaval2785** [comment]
My idea is to segregate code and data.

Code in pywork.
Data in orig.

**Comment by gasyoun** [comment]
> My idea is to segregate code and data.

Full support.

**Comment by funderburkjim** [comment]
> segregate code and data.

I like the idea of having a csl-orig for the **digitizations** ---   These are after all the primary gold of the sanskrit-lexicon site.

However,  for everything else, it is difficult and somewhat arbitrary to separate code and data.   For instance, the abbreviation expansions that we have for some dictionaries are independent data.  Similarly, the list of file names for the scanned images (web/webtc/pdffiles.txt) are data required for displays.
The dtds are data, the xmlheader files are data.   And there are probably other examples, including hwextra.

Determining these requisite pieces, both data and software, is what I'm currently thinking about,
along with where to put them in csl-pywork.

I think all the above-mentioned data files, as well as the hwextra lists, should be kept within the csl-pywork directory.

**Comment by drdhaval2785** [comment]
@funderburkjim Any final call on this hwextra files?
Currently they are residing in csl-orig and have been doing well.
Let's close the issue.

**Comment by funderburkjim** [comment]
> Any final call on this hwextra files?

NO.   I had to review the situation to be sure the orig/v02/xxx/xxx_hwextra.txt files are really being used!

And they are.  

Here's the logic.
Let xxx be a dictionary code.
We start with an invocation of generate_dict.sh such as
`sh generate_dict.sh xxx OUTDIR`    
OUTDIR is specified relative to the directory of csl-pywork/v02, the location of generate_dict.sh:
* in redo_cologne_all.sh, OUTDIR is  '.../../XXXScan/2020/'
* in redo_xampp_all.sh, OUTDIR is  '../../xxx'

For testing purposes, OUTDIR could be something else, such as 'tempdir/xxx'.

* `generate_dict.sh xxx OUTDIR` first does does `generate_orig.sh xxx OUTDIR`
* generate_orig.sh uses generate.py to copy files according to specifications in inventory_orig.txt.
   `python generate.py "$dict" inventory_orig.txt _ '../../csl-orig/v02/${dictlo}' $outdir`
   The 2nd parameter `../../csl-orig/v02/${dictlo}` is the directory which is the PARENT to the
   file to be copied as that file occurs in the specification line of inventory_orig.txt. 
   The 3rd parameter `$outdir`  is the target of copied files (OUTDIR).
   For example,
    `*:${dictlo}.txt orig/${dictlo}.txt:CD` is one specification in  inventory_orig.txt.
   There are *three* fields (colon-delimited):
   * This specification matches any dictionary code xxx (since first field is '*')
   * The second parameter `${dictlo}.txt orig/${dictlo}.txt`  specifies the *from* and *to* files
     for the copy (*from*[space]*to*`)
     * The *from* file (`${dictlo}.txt` is specified relative to PARENT. 
        This resolves to `../../csl-orig/v02/${dictlo}/${dictlo}.txt` or,
        `../../csl-orig/v02/xxx/xxx.txt orig`
     * The *to* file (`orig/${dictlo}.txt`) is specified relative to OUTDIR.
        This resolves to `OUTDIR/orig/${dictlo}.txt` or,
        `OUTDIR/orig/xxx.txt`.   
     * to summarize (for local installation, for dictionary mw), we effectively
        copy `../../csl-orig/v02/mw/mw.txt`  to `../../mw/orig/mw.txt`
  * The third parameter of our example is 'CD' which means 'copy distinct', as opposed to
     copy as a template.
* Similarly, for hwextra.txt. The specification in inventory_orig.txt 
   `*:${dictlo}_hwextra.txt pywork/hwextra/${dictlo}_hwextra.txt:CD`
   taken for dictionary mw and a local installation means that we effectively 
   copy   `../../csl-orig/v02/mw/mw_hwextra.txt`  to `../../mw/pywork/hwextra/mw_hwextra.txt`
* Similarly, xxx-meta2.txt and xxxheader.xml are copied from orig to the agreed-upon location
   in pywork.
* Finally, other scripts run later by generate_dict.sh are written to use the files in the OUTDIR
   that we just copied from csl-orig.

This elaborate review of the logic confirms that, *yes*, the hwextra files in csl-orig are used, and
are the primary source of the hwextra information.
Agree with closing issue.

**Comment by gasyoun** [comment]
> This elaborate review of the logic confirms that, yes, the hwextra files in csl-orig are used, and
are the primary source of the hwextra information.

Read is a thriller.
