### ISSUE TITLE
YAT:  changes during verb study

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#201]
These changes were made during identification of verbs in YAT.

## print changes
```
     L=3044, abakIrRin -> avakIrRin
     L=3108, abacUrRita -> avacUrRita
     L=3133, abaqIna -> avaqIna
     L=3145, abadaMSa -> avadaMSa
     L=3154, abadAhezwakApaTa -> avadAhezwakApaTa
     L=3160, abadraNka -> avadraNka
     L=3167, abaDIra -> avaDIra
     L=3212, abaBinna -> avaBinna
     L=3257, abarohin -> avarohin
     L=3267, abalIQa -> avalIQa
     L=3273, abalepa -> avalepa
     L=3280, abalokita -> avalokita
     L=3285, abaSizwa -> avaSizwa
     L=3311, abasavya -> avasavya
     L=3439, abidyA -> avidyA
     L=3495, abiSeza -> aviSeza
     
     L=16245, qiv -> qib
     L=17355, tav -> tev
     L=30667, mlacCa -> mlecCa
     L=32702, lAc -> loc
     L=42338, sUk -> sUc
```
The first batch of 'b' -> 'v' changes were noticed when considering the erroneous 'abaDIra'.
The print has the little cross-bar of a Devanagari 'b', so it this is a print change.  The others
were similarly errors in the print.
![image](https://user-images.githubusercontent.com/6393033/77240273-6f15a500-6bba-11ea-89eb-c38cd3cfffb9.png)

**Comment by funderburkjim** [comment]
## typos
These changes were errors in the digitization, not in the printed page.
```
     L=10204, kuny -> kunT
     L=12823, galgalati -> gal 
     L=22269, pa -> pac
     L=32622, xYc -> lfYc
     L=42812, stumm -> stumB
```

**Comment by gasyoun** [comment]
> similarly errors in the print.

If such a walk can gather hundreds of errors, I'm afraid to think how many are still there in the wild.
