### ISSUE TITLE
BUR: additional abbreviation markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#208]
Several cases were noticed in Burnouf where the digitization (bur.txt) failed to have markup for abbreviations.   
A rough summary is:
```
dén. 100  cases dénominatif.     This abbreviation now marked as <ab>dén</ab>
interj. 34  cases interjection.   This abbreviation now marked as <ab>interj.</ab>
f1 7  cases. First future.  Here, a missing period was added , resulting in <ab>f1.</ab>
f2 8  cases. Second future.  Here, a missing period was added , resulting in <ab>f2.</ab>
```
I didn't check if the missing periods (f1, f2) were typos or print changes. Too minor a detail.

For dénominatif and interjection also added to 'burab' in csl-pywork/v02, so tooltips will
be available in displays.

**Comment by gasyoun** [comment]
> I didn't check if the missing periods (f1, f2) were typos or print changes. Too minor a detail.

Agree.
