### ISSUE TITLE
MW: insert spaces between some markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#210]
In several places in the MW display, sanskrit text needs to be separated from other text.
For example, before a change:
![image](https://user-images.githubusercontent.com/6393033/78848914-17ac6d00-79e1-11ea-8aa1-64b5bcad526f.png)

And after a change:
![image](https://user-images.githubusercontent.com/6393033/78848987-43c7ee00-79e1-11ea-9999-c2b63bd14bce.png)

**Comment by funderburkjim** [comment]
Two kinds of cases were identified and changed:
* insert a space  `</s><ls>`  -> `</s> <ls>`.   The example `aDri` is of this type.
  * 52 such cases changed
* insert a space `</ls><s' -> `</ls> <s`.   
  * 3 such cases changed.

**Comment by gasyoun** [comment]
> sanskrit text needs to be separated from other text.

There are a few more in the older issues, still great.
