### ISSUE TITLE
CCS: numerous changes

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#212]
These changes were made during the investigation of verbs in CCS.
Most are trivial changes, and all are viewed as typos.

In a small number of entries, there was found to be duplicated and slightly garbled text; in these,
the duplicate lines were removed.   This kind of problem is peculiar to the CCS digitization, and 
similar instances were found several years ago.

One such example is vart (L=21481),  and I think vas (L=21634) is another.

**Comment by funderburkjim** [comment]
The commit is [d615368](https://github.com/sanskrit-lexicon/csl-orig/commit/d7153688e35b3fb23147e9323ebaaf5397f36245)  at old line number 99595.

**Comment by gasyoun** [comment]
> Most are trivial changes, and all are viewed as typos.

Understood. Quite a few.
