### ISSUE TITLE
BEN: vocalic 'r' changes

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#217]
While identifying Sanskrit verbs in Benfey dictionary, noticed an error relating to long-short vocalic 'r'.
Specifically, noticed this error in the AS-IAST conversion:
```
'ṛ10' should be 'ṝ' (220 instances)
'Ṛ10' should be 'Ṝ' (32 instances)
```

In a few cases, the SLP1 spellings of headwords also needs changing:
```
L=3755, kf -> kF  (scatter)
L=3756, kf -> kF  (kill)
L=3757, kf -> kF  (know)
L=3758, kft -> kFt (= mw kIrt: to celebrate)
L=9172, pf -> pF (fill)
L=16356, sf -> sF  (see svF)
```
All the above changes considered 'typos'.

Two print changes also made (and duly noted in csl-corrections -- ben_printchange.txt
```
L=6043, {%tṝ,%} -> {%TṜ,%}  (this is verb. so should be upper case. print change
L=9170, {%pṝṣṭhānuga,%} -> {%pṛṣṭhānuga,%} SHORT vocalic r.  print change
```

**Comment by gasyoun** [comment]
> Two print changes also made (and duly noted in csl-corrections

Oh, back to full documentation.

> noticed an error relating to long-short vocalic 'r'

Timely catch.
