### ISSUE TITLE
MW: L=91840, dAvadahanajvAlAkalApaya

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#218]
This typo found when studying Benford verbs:
```
old:
dAvadahanajvAlAkalApaya
new:
dAvadahanajvAlAkalApAya   
                                      *
```
![image](https://user-images.githubusercontent.com/6393033/80646120-28795d00-8a3a-11ea-8a91-f2d8d1610588.png)

**Comment by gasyoun** [comment]
> Benford verbs

Long live Benfey.
