### ISSUE TITLE
skd:8663, etc.  (kamma -> karmma)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#224]
date:	03/06/2020 03:23:50
dict:	skd
Lnum:	8663
hw:	कृष्टपच्यः
old:	कम्म- LB कर्त्तरि
new:	कर्म्म- LB कर्त्तरि
comm:	Typo. This typo is seen in the scanned version also. But I am sure this is a typo

**Comment by funderburkjim** [comment]
print change: kamma -> karmma

![image](https://user-images.githubusercontent.com/6393033/80850804-d1b38500-8beb-11ea-8f8d-668cd3f42ff7.png)

**Comment by funderburkjim** [comment]
## Several other 'kamma' -> karmma:

### 1. L=51, akarmmA.   typo
nAsti kamma -> nAsti karmma

![image](https://user-images.githubusercontent.com/6393033/80850864-438bce80-8bec-11ea-928a-888b2e602391.png)

## 2.  L=59, akAraRam  print change
na cArpitaM kamma -> na cArpitaM karmma

![image](https://user-images.githubusercontent.com/6393033/80850959-b85f0880-8bec-11ea-9155-8b0839b2a9a8.png)

**Comment by funderburkjim** [comment]
## 3. 2868, aSvinO  (print change)
bahuBiH kammaBir -> bahuBiH karmmaBir

![image](https://user-images.githubusercontent.com/6393033/80851048-42a76c80-8bed-11ea-8d16-7b9a58af63fc.png)

## 4. 6745, karmmizWaH (print change)
kamma + izWan  -> karmma + izWan 

![image](https://user-images.githubusercontent.com/6393033/80851140-ccefd080-8bed-11ea-8de1-f6c6fecdfa14.png)

**Comment by funderburkjim** [comment]
## 5. 8338, kuSaRqikA (print change)
kAmyakammArTaM -> kAmyakarmmArTaM

![image](https://user-images.githubusercontent.com/6393033/80851267-ab431900-8bee-11ea-93e0-2f998ba02eac.png)


## 6. 8952, koNkaRaM (print change)
kamma-kArE  -> karmma-kArE

![image](https://user-images.githubusercontent.com/6393033/80851381-5f44a400-8bef-11ea-900b-ec3cf62af042.png)

**Comment by funderburkjim** [comment]
## 7. 11018, guRIBUtavyaNgyaH    ???
No change made here:
Can make no sense of this.  @drdhaval2785  or @SergeA  -- any help?
`<>GarakammabAbbAqAe bahUe sIanti aNgAiM .`   [scan](http://localhost/cologne/csl-apidev/servepdf.php?dict=skd&page=2-337), middle column.

![image](https://user-images.githubusercontent.com/6393033/80851644-fceca300-8bf0-11ea-9bbf-889f634e8974.png)

**Comment by funderburkjim** [comment]
## 8. 24610, BagolaH  (print change)

vizkammaKaRqaM -> vizkarmmaKaRqaM

![image](https://user-images.githubusercontent.com/6393033/80851807-dda24580-8bf1-11ea-92f1-11e14a32ab55.png)

## 9. 36929, zawkarmmA  (typo)
kammARi -> karmmARi

![image](https://user-images.githubusercontent.com/6393033/80851896-6d47f400-8bf2-11ea-82e8-359190861737.png)

**Comment by funderburkjim** [comment]
## 10. 37769, sannyAsI  (typo)

kAMmaM -> kAmaM     (This is different error. It was noticed because 'kAMma' matches a
case-insensitive search for 'kamma'

![image](https://user-images.githubusercontent.com/6393033/80852006-0b3bbe80-8bf3-11ea-8908-9ba20ea2ac34.png)

**Comment by gasyoun** [comment]
So many, good that most not at headword level.
