### ISSUE TITLE
mw:110831– 110837

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#235]
date:	03/30/2020 04:22:02
dict:	mw
Lnum:	110831– 110837
hw:	niṣkūṭa
old:	niṣkūṭa
new:	niṣkuṭa
comm:	Typo

**Comment by funderburkjim** [comment]
This has already been corrected in the 2020 data.
![image](https://user-images.githubusercontent.com/6393033/80882341-b3509680-8c8a-11ea-9903-b0c04badd306.png)

However, using the 2014 display,  the error is found:
![image](https://user-images.githubusercontent.com/6393033/80883131-eb57d980-8c8a-11ea-9acc-d7b17b287398.png)


![image](https://user-images.githubusercontent.com/6393033/80883672-12161000-8c8b-11ea-86bf-73adab54ba2b.png)
![image](https://user-images.githubusercontent.com/6393033/80883931-23f7b300-8c8b-11ea-9bff-3753dbfde4ee.png)

**Comment by funderburkjim** [comment]
Unfortunately, the user submission has no email, so we can't tell the user to use the new displays.

**Comment by gasyoun** [comment]
> so we can't tell the user to use the new displays.

Kill or 301 redirect the older ones.
