### ISSUE TITLE
mw:all

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#244]
date:	04/12/2020 05:24:21
dict:	mw
Lnum:	all
hw:	all
old:	NA
new:	NA
comm:	I need to see more than 1000 entries. E. g. I want to look up all words that have the letters क्र as substring. Now I am able to see only 1000 entries from अकडमचक्र to क्रोडकान्ता| There are still all the क्रs preceded वर्गीय and अवर्गीयव्यञ्जनs except those within the first 1000. As I remember, till about one or two years ago there was the ALL option. Please put it back. Or suggest me a way looking up the next 1000, and the next 1000 and the next till सह’क्र’म्य. Thanks in advance.

**Comment by funderburkjim** [comment]
This relates to the MW advanced search display.

The user's memory is right.  We used to have an 'all' choice.

But this sometimes crashed the Cologne server, so we had to put a limit in.

The user also mentions the 'next' feature of advanced search.

This is probably the best solution .  When I did this, there were slightly less than 3000  (1000 to start,
next another 1000, next a final 937).

These cannot all appear within one browser window,  but it would be possible to use multiple
browser windows (or tabs) to get all the results in three browser tabs.
By copy/pasting from these tabs into a text editor, one could get all the data.

By some custom programming,  one could remove the barrier in a local installation.

**Comment by gasyoun** [comment]
> but it would be possible to use multiple
browser windows (or tabs) to get all the results in three browser tabs.

Does not sound smart enough.

> By some custom programming, one could remove the barrier in a local installation.

Can't it be changed manually by user in URL itself?

**Comment by funderburkjim** [comment]
> Can't it be changed manually by user in URL itself?

No, this would allow user to crash server.  Not a good idea.

**Comment by funderburkjim** [comment]
The user sent this interesting reply regarding why he wanted the list :

```
I regularly compose metrical verses in Kannada (the language of Karnataka state, south India, 
whose capital is Bangalore) for www.padyapaana.com where is also a Sanskrit section 
( http://padyapaana.com/?cat=7 ) . Please see if you will find it interesting.
 Typical of Kannada versification is that the second letter should be the same in all the lines; 
it is slightly different from limerick where the rhyming happens at the end of the lines. 
Suppose I select the first words as चक्र, then I will need words like तक्र, नक्र, वक्र, शक्र etc. 
for the subsequent lines.  But I can think of only these five. 
I want much more of them so that I can compose a fine verse. 
Even if क्र were not to be the second letter of the word, even if it were the third, fourth, fifth etc.,
 I can do खण्डप्रास, i. e. I can split a word and take the first part of it to the end of the previous
 line so that I can have क्र as he second letter of the current line. 
E. g. अन-तिक्रम। It is a very individual requirement. 
There may be no others who may want this facility. so please don't take undue pains. 
Considering that there was the ALL option earlier, I thought you may just 'put it back'.
 Thanks for your concern.
```
Here's the url: http://padyapaana.com/?cat=7

**Comment by gasyoun** [comment]
Lovely idea. How do we know what letter is the `second letter of the word`, any clue?

**Comment by prasaadu** [comment]
Namaskar gasyoun, the selection of the opening द्वितीय-प्रासाक्षर is the prerogative of the versifier. Then on s/he has to stick to it in the rest of the (three) lines. My immediate next post is a poem by a scholarly friend of mine who has attempted this in Sanskrit. The introduction there will serve to explain.

**Comment by prasaadu** [comment]
A beautiful kannaDa song translated to Sanskrit by a young Sanskrit poet living in our midst, Dr. Shankar Rajaraman. There are very few in Karnataka who wouldn't have heard this beautiful song. It has been mellifluously translated to Sanskrit.

Here is what Shankar got to say: The Kannada song ಗೋವಿನ ಹಾಡು (Song of the cow) is based on a story narrated in the padmapurANa about how a cow risked her life to follow the principles of truth and honesty. I have tried to incorporate द्वितीयाक्षरप्रास in most stanzas as this is in keeping with the original. I have also followed the metrical structure of the Kannada song.

धरणिमण्डलमध्यवर्तिनि
सरसतरकर्णाटविषये 
स्फुरति कालिङ्ग इति गोपो
हरति यस्य कथा जनम्॥१॥

तरुणतरमाकन्दचरणे
मुरलिकां वादयति गोपः 
सुरभिकुलमाह्वयति मुदितो
विरचितोज्ज्वलवलयकम्॥२॥

एहि गङ्गे गौरि तुङ्गे
एहि जननि शुभान्तरङ्गे
एहि भद्रे पुण्यकोटि
त्वमिति गायति गोपतिः॥३॥

गोपतेराकर्ण्य शब्दं
प्राप धेनुकुलञ्च सकलं
सा पयोभिरपूरि दोह-
स्थापिता च नवा घटी॥४॥ पुण्यकोटिकथेयमत्र तु सत्यमेकं दैवतम्॥

विकटगिरिमध्ये बुभुक्षा-
विकलमतिरद्भुतसुनामा
निकटभुवि कटकस्य वसति
प्रकटकोपो व्याघ्रराट्॥५॥

अटति रोषवशेन गर्जति
झटिति निपतति चटुलशीले 
पटुरभसि शार्दूलराजे
रटति चकितो गोगणः॥६॥

वत्सकस्मरणेन सोत्सव-
हृत्सुरभिरथ पुण्यकोटी
मत्सुताय पयो ददामी-
त्युत्सुका पुरतो ययौ॥७॥

फलितमिह भोजनमितिच्छल-
मलिनहृदयो व्याघ्रपतिरपि ।
अलमकृत पथि विघ्नमविरल-
कलितसत्वरपदगतिः॥८॥ पुण्यकोटिकथेयमत्र तु सत्यमेकं दैवतम्॥

व्याघ्र उवाच
उपरि तव निपतामि धेनो
सपदि जठरविदारणे पटु-
रपरिमितपरिकुपितमतिरिति
लपति नखरायुधपतिः॥९॥

धेनुरुवाच -
व्याल विज्ञापनमिदं शृणु
बालवत्सो वसति गोष्ठे
कालमल्पं स्थातुमर्हसि
लालये स्तन्येन तम्॥१०॥

व्याघ्र उवाच -
यदि बुभुक्षावसरलब्धां
सदय इह मुञ्चामि भिक्षां
वद पलायनपण्डिता किमु
पदमुपैष्यसि पुनरिदम्॥११॥

धेनुरुवाच -
सत्यमेव मदीयपितरौ
सत्यमेव मदीयबन्धुः
सत्यवाग्गलिता न यामि
स्तुत्यतां परमात्मनः॥१२॥

धेनुर्वत्सं प्रत्युवाच -
त्वामरे खादामि निहतां
मामिति व्याघ्रे भणति सति 
एमि पुनरिति भाषया त्वत्-
प्रेमतोऽस्मि सुतागता॥१३॥

वत्सो धेनुं प्रत्याह-
स्तनमहह पास्यामि कस्या
जननि कामवलम्ब्य वर्ते
अनुदिनं शाययतु का तव
तनयमयि के मम हिताः॥१४॥

धेनुर्धेनूः प्रत्युवाच-
मातरो महिता भगिन्यः
कातरो मम हन्त वत्सः
नेतरोऽयमनाथशिशुरिति
जातकरुणं पश्यत॥१५॥

धेनुर्वत्सं प्रत्युवाच-
जीवसि त्वमनाथजीवित-
माविशामि व्याघ्रमुखमयि
नावयो ऋणशेष इति सा
तावदस्वजत स्वजम्॥१६॥

धेनुरपि सुतविप्रयुक्ता
सा निरस्तविलम्बना गिरि-
सानुकन्दरमेत्य सरभस-
मेनमाह नखायुधम्॥१७॥

धेनुर्व्याघ्रं प्रत्युवाच -
खण्डमिदमिह मांसमिदमिह
पिण्डमपि हृदयस्य रुधिरो-
द्दण्डमिह शार्दूल चण्डपि-
चण्ड भक्षय तृप्तये॥१८॥

व्याघ्रो धेनुमुवाच -
त्वमयि मम सहजासि भद्रे
किमिह मे तव मारणादिति
स महितार्थमुदीर्य निपत-
न्निमिषति स्म नखायुधः॥१९॥ पुण्यकोटिकथेयमत्र तु सत्यमेकं दैवतम्॥

**Comment by prasaadu** [comment]
Notice that in the first two verses, the second letter of each line is र; in the third verse it is ह; in the fourth it is प and so on.

**Comment by prasaadu** [comment]
Please also note that in the seventh verse, the second letter is a compound consonant त्स. There are other such verses.

**Comment by gasyoun** [comment]
> second letter of each line is र; in the third verse it is ह; in the fourth it is प and so on.

Hardly I can grasp the logic. Would love to see an even more detailed explanation, to understand what can be done to help you.

**Comment by prasaadu** [comment]
Dear MG,
I have stated everything clearly. To put it simply, IF POSSIBLE please
reinstate the ALL in the number series (5 20 50 100 200 500 1000) of search
entries. You have stated that the system hangs at that option. So please
forget it. I can manage without it. Thanks for your concern.
svasti
Prasad

**Comment by gasyoun** [comment]
> I can manage without it. 

Can we premake any lists of words?

**Comment by prasaadu** [comment]
Oh no. I will be needing a few every week
