### ISSUE TITLE
STC: Abbreviation 'not.'

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#265]
About 900 instances of the abbreviation 'not.' in STC.  Now marked as `<ab>not.</ab>`.

Also [stcab_input](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/stc/pywork/stcab/stcab_input.txt) has added line
`not.	<id>not.</id> <disp>notamment</disp>`.

Thanks to Caujolle for the abbreviation expansion.

**Comment by gasyoun** [comment]
> Caujolle for the abbreviation expansion.

Not listed in Preface?

**Comment by funderburkjim** [comment]
'not.' is NOT listed in STC's list of abbreviations in preface.
```

<P>moy. moyen (voix moyenne).

<P>n. nom.

<P>nom(in). nominatif.

<P>nt. neutre.

<P>num. numéral.

<P>onom. onomatopée.

```

**Comment by gasyoun** [comment]
> NOT listed in STC's

Oh, interesting.
