### ISSUE TITLE
bur: anDa -  print enhancement 

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#266]
This note an outgrowth of the print change made in #261.

Caujolle mentions that there are still some unwanted blank lines in displays.  An example is in
'anDa'

![image](https://user-images.githubusercontent.com/6393033/81107608-7a602e00-8ee5-11ea-969b-d3c680fc7c4e.png)

## a hard problem
The solution to this problem is difficult, and I don't want to tackle it now.
This note aimed to keep the problem visible, and to make an initial investigation into the
source of the problem.

**Comment by funderburkjim** [comment]
Here is the generated xml for the anDa example:
```
<H1><h><key1>anDa</key1><key2>anDa</key2></h><body><s>anDa</s>  
<i>andha</i> <ab>a.</ab> aveugle, au propre et au <ab>fig.</ab> 
<div n="3"> caché, secret, occulte. </div>
    THE NEXT TWO LINES ARE WHERE THE PROBLEM STARTS
<div n="2">— <ab>S.</ab> <ab>n.</ab> obs- curité.  [Page029-2]  </div>
<div n="P"><i>andhaka</i> <ab>a.</ab> aveugle; caché. </div>

<div n="3"> <ab>Np.</ab> de pays et de peuple de la famille de Yadu.  </div>
<div n="P"><i>andhakāra</i> <ab>m.</ab> <ab>n.</ab> <i>(kṛ)</i> obscurité.  </div>
<div n="P"><i>andhakāramaya</i> <ab>a.</ab> (<ab>sfx.</ab> <i>maya)</i> obscur, ténébreux.  </div>
<div n="P"><i>andhakūpa</i> <ab>m.</ab> caverne obscure. Puits.  </div>
<div n="P"><i>andhatamasa</i> <ab>n.</ab> <i>(tamas)</i> obscurité noire.  </div>
<div n="P"><i>andhamūṣikā</i> <ab>f.</ab> <ab>esp.</ab> d'herbe.</div></body>
<tail><L>809</L><pc>029,1</pc></tail></H1>
```

**Comment by funderburkjim** [comment]
## HTML generated
```
<br/>
<span ...> caché, secret, occulte. </span>
<br/>
<span ...>— <span ...>S.</span> <span ...>n.</span> obs- curité.  
<br/>
[Page029-2]
<br/>  
</span>
<br/>     <<<<< THIS causes the extra blank line.
<span ...><i>andhaka</i> 
ETC
```

**Comment by funderburkjim** [comment]
The problem is difficult to solve with the current logic, 
because two different pieces of code are adversely interacting.
One piece of code adds a break before and after `[Page...]`, which is usually what is wanted

Another piece of code adds a break before the `<div n="P">`,  which is also usually what
is wanted.

However, in the current situation,  these two pieces together insert two page breaks after
`[Page...]`, which is not wanted.

We want to solve this problem, without introducing other problems.
This appears to me to be a thorny problem.  And since it only results in a relatively minor
aesthetic ugliness in the display,  I don't feel an urge to tackle a solution at the moment.

**Comment by funderburkjim** [comment]
## An afterthought solution
It is easy to just remove `[Page029]`  for Burnouf:

![image](https://user-images.githubusercontent.com/6393033/81112835-4557d980-8eed-11ea-949e-26d30b9eccc0.png)

Is this a satisfactory solution?

What do others think?

Currently, this solution is just in my local installation (changes to basicdisplay.php).

**Comment by gasyoun** [comment]
> This appears to me to be a thorny problem. And since it only results in a relatively minor
aesthetic ugliness in the display, I don't feel an urge to tackle a solution at the moment.

Agree.

> Is this a satisfactory solution?

Yes.

**Comment by funderburkjim** [comment]
Caujolle's comment:
```
I don't really know. I never use it but probably because they are not a link. 
But of course it would also be nice to keep it but then they should at least be 
made as a link, then they can be useful; that is, they should be 
in same light and less light grey like it is used for that in the head of the page 
for each headword. 
Also there should be a blank after "Page" that is, before the number.
```
```
For Stchoupak same, look for deva for example, or mahA.
```

For now, I will stay with the solution of not printing the Page breaks in Burnouf.
Thanks for feedback to help me decide.

Will look into doing the same thing for Stchoupak, if needed.

**Comment by funderburkjim** [comment]
Made same change regarding `[Pagexxx` in STC.
