### ISSUE TITLE
MW: L=121944, pAdapASI

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#267]
Print change 'Kaquka' to 'KadukA'

![image](https://user-images.githubusercontent.com/6393033/81222052-b19c1100-8fb1-11ea-92b1-6cb388951663.png)

MW has an entry for 'KaqukA'  , which ultimately is consistent in sense with 'pAdapASI':
KaqukA -> KaqatU -> KaWU

![image](https://user-images.githubusercontent.com/6393033/81222651-9d0c4880-8fb2-11ea-9400-64d2a024fc8b.png)

![image](https://user-images.githubusercontent.com/6393033/81222728-c1682500-8fb2-11ea-96a1-878cf6b68bb5.png)

So, Monier-Williams must have intended a reference to 'KaqukA', not 'Kaquka'.

Hence the print change.

**Comment by gasyoun** [comment]
> Hence the print change.

Hence we love Jim.
