### ISSUE TITLE
MW: add homonym markup

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#268]
There are many instances like:
`for 1. See ...`   As example:

![image](https://user-images.githubusercontent.com/6393033/81223676-5fa8ba80-8fb4-11ea-981a-2accf22ad79f.png)

This entry is for the second homonym of uttaraMga,  and the `for 1. See` text means that for the first homonym, the reader should look in another place in the dictionary (in this case, the second column  of page 178.

In the digitization of MW,  the `hom` tag is intended to enclose numbers that represent homonymous variants.  In our example, both the '2.' and '1.' numbers are tagged as intended:
```
<L>31381<pc>179,1<k1>uttaraMga<k2>ut-taraMga<h>2<e>1
<hom>2.</hom> <s>ut-taraMga</s> ¦ <lex>m.</lex> 
(for <hom>1.</hom> See <pcol>p. 178, col. 2</pcol>), 
a high wave, <ls>Kathās. 123, 196</ls><info lex="m"/>
```

There are 150 matches to `for <hom>[1-9][.]</hom> See`.

However, there are 593 cases where the `<hom>` tag is missing (`for [1-9][.] See` .

This correction adds the hom markup to these 593 cases.

**Comment by funderburkjim** [comment]
Other variants where `<hom>` tags added.
* `for 1. and 2. `  16 cases
* `for 2. and 3.`   10 cases
* `for 1. and 3.`     5 cases
* `for 1. 2.`           11 cases
* and a few more variants

**Comment by funderburkjim** [comment]
## still some missing homonym tags.

There are definitely  additional numbers `x.` which represent homonym variants but which are as
yet unmarked with the `<hom>` tag.

For instance there are 892 cases of pattern `[1-9][.] <s>`.
But not all of these numbers should be marked as homonyms.  For instance, under headword 'akz',
`1. 5.` are conjugation class numbers, not homonymn numbers:
```
perhaps a kind of old <ab>Desid.</ab> of √ <hom>1.</hom> <s>aS</s>) 
<ab>cl.</ab> 1. 5. <s>akzati</s>, <s>akzRoti</s>     <<<not homonym numbers
```

Maybe some energetic soul will go through these one by one and add homonym tags where
needed.

**Comment by gasyoun** [comment]
> Maybe some energetic soul will go through these one by one and add homonym tags where
needed.

Let me ask my students.
