### ISSUE TITLE
MW: reposition nAnAvasTa

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#271]
This correction courtesy G. Huet.

```
Just found a mistake in the aggregation of MW supplements: the two entries

 नानावस्थ [ naanaavastha ] [ naan-aavastha ]  m. f. n. differently conditioned, Lit. Kāvyâd.( 1329,2 ) 

  नानाश्रय [ naanaazraya ] [ naan-aazraya ]  m. f. n. wearing different forms (or, "resorting to various means" ), Lit. Bcar. xiii, 18.( 1329,2 ) 

should be placed after entry 

नाना [ naanaa ] 

at their respective place in the orthographic order of compounds with iic nAnA
```

**Comment by funderburkjim** [comment]
## nAnAvasTa
```
old:  
<L>105507.1<pc>1329,2<k1>nAnAvasTa<k2>nAn—AvasTa<e>3
<s>nAn—°A<srs/>vasTa</s> ¦ <lex>mfn.</lex> differently conditioned, <ls>Kāvyâd.</ls><info n="sup"/><info lex="m:f:n"/>
<LEND>
new:
previous: <L>105578<pc>535,2<k1>nAnAvarRAkfti<k2>nA/nA—varRAkfti<e>4

<L>105578.1<pc>1329,2<k1>nAnAvasTa<k2>nAn—AvasTa<e>3
<s>nAn—°A<srs/>vasTa</s> ¦ <lex>mfn.</lex> differently conditioned, <ls>Kāvyâd.</ls><info n="sup"/><info lex="m:f:n"/>
<LEND>

next: 
<L>105579<pc>535,2<k1>nAnAvAdasaMgrahagranTa<k2>nA/nA—vAda-saMgraha-granTa<e>3
```

**Comment by funderburkjim** [comment]
## nAnASraya
```
old:
<L>105507.2<pc>1329,2<k1>nAnASraya<k2>nAn—ASraya<e>3
<s>nAn—°A<srs/>Sraya</s> ¦ <lex>mfn.</lex> wearing different forms (or, ‘resorting to various means’), <ls>Bcar. xiii, 18</ls>.<info n="sup"/><info lex="m:f:n"/>
<LEND>

new:
previous: <L>105588.2<pc>535,2<k1>nAnASAstrIya<k2>nA/nA—SAstrIya<e>4


<L>105588.3<pc>1329,2<k1>nAnASraya<k2>nAn—ASraya<e>3
<s>nAn—°A<srs/>Sraya</s> ¦ <lex>mfn.</lex> wearing different forms (or, ‘resorting to various means’), <ls>Bcar. xiii, 18</ls>.<info n="sup"/><info lex="m:f:n"/>
<LEND>

next: <L>105589<pc>535,2<k1>nAnAsaMvAsika<k2>nA/nA—saMvAsika<e>3

**Comment by gasyoun** [comment]
@funderburkjim is the pattern searchable? Have not you tested the alphabeticalisation before?

**Comment by funderburkjim** [comment]
Notice the form `<info n="sup"/>` in each of these words.  This markup indicates that the entry
is from the supplement.

Thus, a list could be generated of all the supplement entries.

The positioning of the supplement records was done by someone who knew Sanskrit, but was not as familiar with mw.xml.  Thus, there have been lots of problems, similar to the above.

The 'correct' positioning of supplement entries is often difficult to decide.   It would be good for
someone to review all the cases.  Better to get such a someone first.

**Comment by gasyoun** [comment]
> It would be good for someone to review all the cases. Better to get such a someone first.

Maybe a list should come first?

**Comment by funderburkjim** [comment]
No,  someone needs to adopt the problem first.   Then, working with that someone,  I can help develop -- in conjunction with that someone -- useful listings to aid the analysis.  Sort of like the collaboration with @Shalu411 on skd-vcp verbs.

**Comment by Andhrabharati** [comment]
is that someone **Andhrabharati**, having taken up looking into the full annexure pages under MWS folder?

**Comment by funderburkjim** [comment]
Yes , it certainly is due to AB's help that the generalization of this problem is being attended to now.

Don't think this particular issue needs to remain open.

Refer to https://github.com/sanskrit-lexicon/MWS/issues/80  and other 'fresh look' issues.
