### ISSUE TITLE
VCP: bamUva -> baBUva

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#272]
This was noticed while examining https://github.com/sanskrit-lexicon/SKD/issues/9#issuecomment-626819209.
On the next line:

![image](https://user-images.githubusercontent.com/6393033/81615856-594d8080-93b0-11ea-9121-21a8efc09e87.png)

This is certainly the 3s perfect of 'BU', with slp1 spelling of 'baBUva'.   

There are 11 such erroneous spellings:
```
11 matches for "bamUva" in buffer: vcp.txt
  10755:<>sinDuSva tasmAdamftamamftaraSmiH SrISva yasmAdbamUva . mahi-
  92885:<>EYjizWa . IYjAm--bamUva Asa cakre! IYjitam . ayam
  96989:<>saMbamUvatuH . devakaScograsenaSca devagarBasamAvuBO . navograse-
 124108:<>pakze u(U)rjAm bamUva Asa cakAra . kta u(U)rjjita, vfdDe
 124965:<>ozati OzIt ozAm bamUva--Asa--cakAra uvoza .
 126635:<>UzAm bamUva Asa cakAra . UzitaH vyUzaH UzaRaH .
 131195:<>ArmPIt--ArPIt fmPAm--bamUva Asa cakAra AnarPa
 138424:<>bamUva Asa cakre . ejakaH ejitavyaH ejitA . ejitaH
 140417:<>Ojijat ta ojayAm bamUva Asa cakAra cakre . ojitaH
 146121:<>kawASabdo bamUva sumahAtmanoH” BA0 va0 157 a0 .
 146774:<>acakaRWat ta akaRWIt . kaRWayAM bamUva Asa cakAra
```
In all these cases, changing 'bamUva' to 'baBUva'.

Will consider as typos, since the print could be a poorly formed Devanagari 'B'.

**Comment by funderburkjim** [comment]
## Also, a print change in VCP related to the same Uza entry.

```
<L>10344<pc>1393,b<k1>Uza<k2>Uza
OLD:
Uza¦ pu0 rUjAyAm BvA0 para0 saka0 sew . Uzati OzIt   <<< pu0
Uza¦ rUjAyAm BvA0 para0 saka0 sew . Uzati OzIt   <<< pu0
NEW:
[Page1394-a+ 38]
<>UzAm baBUva Asa cakAra . UzitaH vyUzaH UzaRaH .
<LEND>
```
pu0 (masculine) is wrong. This is a verb.  as @Shalu411 pointed out.

**Comment by Shalu411** [comment]
> pu0 (masculine) is wrong. This is a verb. as @Shalu411 pointed out.

Thank you so much. Wow. :)

**Comment by Shalu411** [comment]
> ```
> 
> In all these cases, changing 'bamUva' to 'baBUva'.
> 
> Will consider as typos, since the print could be a poorly formed Devanagari 'B'.
Sure! Perfect!! The similarity of the two letters lead to this confusion. And moreover, Print is bad. So well decided. :)

**Comment by gasyoun** [comment]
> Print is bad

Print is a disaster.
