### ISSUE TITLE
Cronjob for stardict generation (was earlier ap90:26303)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#291]
date:	05/21/2020 05:24:21
dict:	ap90
Lnum:	26303
hw:	वियत्
old:	aky - This typo is in the scan too. 'aky' is not a valid word in English
new:	sky
comm:	Typo in the original. You can lookup वियत् in Monier-Williams and confirm that it should be the sky.

**Comment by funderburkjim** [comment]
![image](https://user-images.githubusercontent.com/6393033/84948222-6c432700-b0b9-11ea-96dd-79760ea1f770.png)

Print change made, and added to print changes for ap90.

**Comment by funderburkjim** [comment]
The user further comments:

```
I tend to consume the dictionaries offline on my Android device by using the Stardict sanskrit 
dictionary downloader (as mentioned on your website), but sometimes I use the web interface too.
```

While the web displays are updated as part of the correction process,
the Stardict downloads are not.  Should updating the Stardict downloads be considered
part of the correction process?

**Comment by drdhaval2785** [comment]
It should become part of updation process. A cronjob daily would help.

**Comment by drdhaval2785** [comment]
Updated stardicts to use latest version as on 21 June 2020.

**Comment by gasyoun** [comment]
> A cronjob daily would help.

@drdhaval2785 can you CRON it, please?

**Comment by drdhaval2785** [comment]
Now code is tested OK. Will update from my local machine once a month or so

**Comment by gasyoun** [comment]
So non-CRON manual Dhaval mode?

**Comment by drdhaval2785** [comment]
After the major changes in the text files amd xml files in last two years, the confidence level in script is low. So manual Dhaval mode is safer for the time being. Will automate cronjob after the output is as per requirement consistently.

**Comment by gasyoun** [comment]
> Will automate cronjob after the output is as per requirement consistently.

Understood. Let's plan for a call in early July, can @drdhaval2785 and @funderburkjim ?

**Comment by drdhaval2785** [comment]
# Notes to self
```bash
git diff --name-only `(cat v02/.xampp_last_run)`..`(git rev-parse HEAD)`
```
to identify the differing files between the present HEAD (latest commit) and the one which I manually stored in v02/.xampp_local_run at the end of redo.sh to signify that upto this commit the regeneration has happenned.
In the example, I had stored 15b394c8fc027e28306e8919e04f43cfe1ca1574 in v02/.xampp_local_run and the HEAD is fd70a0c05bfaf3a6ff3cc4f87ad844921b41dd2c .

Differing files are like the ones mentioned below.
```
.gitignore
v02/ben/ben.txt
```

This shows that only these many files were modified between two commits which are of interest to us.
Will tweak the redo scripts to work on only these many dictionaries and no more.
This will make redo quicker, and will not subject unnecessary files to the redo procedure and save time.

**Comment by drdhaval2785** [comment]
# Finding out only the filename from `v02/ben/ben.txt`

```bash
git diff --name-only `(cat v02/.xampp_last_run)`..`(git rev-parse HEAD)` | grep -oP '[\/]\K([^\/]*)(?=[.]txt)'
```

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/redo_xampp_selective.sh is the script.
It takes into account the commits added after the previous run, and updates local display, stardict generation in cologne-stardict and json in csl-json.

**Comment by drdhaval2785** [comment]
It now also updates downstream data at https://github.com/indic-dict/stardict-sanskrit repository for distribution to various stardict users.

**Comment by drdhaval2785** [comment]
# Hurray.

`30 10 * * * bash /var/www/html/cologne/csl-pywork/v02/redo_xampp_selective.sh`
This cronjob was scheduled to run at 10:30 a.m. Indian Standard Time, on my local machine.
Jim had sent YAT corrections vide https://github.com/sanskrit-lexicon/csl-orig/commit/1fdb593e9cabfad686bbbc9ea9793513e69d3045 .


# Expected task:

1. Update my local csl-orig repository based on changes made on Github.
2. Update local xml file of changed dictionary i.e. yat.xml 
3. Update https://github.com/sanskrit-lexicon/cologne-stardict babylon files with the latest changes made in csl-orig repository.
4. Update https://github.com/indic-dict/stardict-sanskrit with the latest babylon files. This takes care of the downstream users depending on [stardict-anskrit-dictionary-updater](https://play.google.com/store/apps/details?id=sanskritcode.sanskritdictionaryupdater&hl=en&gl=US) for updating their dictionary data on their mobiles / computers.
5. Update https://github.com/sanskrit-lexicon/csl-json with latest json file for use by ashtadhyayi.com/ 

# Result:

1. My local csl-orig repository was updated.

```bash
commit 1fdb593e9cabfad686bbbc9ea9793513e69d3045 (HEAD -> master, origin/master)
Author: funderburkjim <funderburkjim@gmail.com>
Date:   Mon Aug 16 13:28:20 2021 -0400

    YAT english word corrections.
    Ref: https://github.com/sanskrit-lexicon/csl-corrections/issues/73
```
2. My local yat.xml was updated.

aMgnatretA was changed to agnitretA in the said commit. The same is transferred to xml file.
```
<H1><h><key1>agnitretA</key1><key2>agni-tretA</key2></h><body><s>agni-tretA</s>  <s>(tA)</s> 1. <i>f.</i> The three fires <br/>of a brāhman householder.</body><tail><L>222</L><pc>005-b</pc></tail></H1>
````
3. cologne-stardict repository was updated via https://github.com/sanskrit-lexicon/cologne-stardict/commit/e45566da9955c9fbca9d7b00868c4aaea753cfbf 
4. stardict-sanskrit repository was updated via https://github.com/indic-dict/stardict-sanskrit/commit/64e6c773283ffe25c871f59baf5c6b991b630861
5. csl-json repository was updated via https://github.com/sanskrit-lexicon/csl-json/commit/708e7a277575c5c70167e51f661165b3eb102a48 

Thus all the criteria which I set for myself got accomplished.
The commit messages are made unique by timestamp.

**Comment by drdhaval2785** [comment]
# Present bugs and road ahead

1. As the script runs on my local machine via cronjob, there are chances that the script may not run at scheduled timing daily, because my computer may be off during that period. Based on googling, it seems that `cron` is not suitable for such kind of jobs. `[anacron](https://linux.die.net/man/8/anacron)` seems to be the preferred cron manager for such tasks on personal computers which are on and off sometimes during the day.
2. The present workflow takes care of only the data portion as far as stardict and json generation is concerned. It does not automate the triggering of changes at `Cologne Server`. But considering the feasibility of `redo_xampp_selective.sh` file for local run, similar file at Cologne server may not be a difficult task. I can work with @funderburkjim to create a similar workflow for updation at Cologne server. Whether we are allowed to do cronjob or not would have to be taken up with the system administrators at Cologne. I was able to run the cronjob on my local machine without `sudo` or `root` privilege. So, this may not be too difficult to be done in Cologne side also.

**Comment by drdhaval2785** [comment]
1. cron has a `@reboot` command which allows the script to run at every reboot of the computer. The redo_xampp_selective.sh script is idempotent. Therefore, there is no difficulty in allowing it to run on every reboot on my laptop. The commit https://github.com/sanskrit-lexicon/cologne-stardict/commit/d6a60c3455a4b81a202db52930ecb6429c6d9ad3 was autogenerated via this reboot facilitu or cron. Seemed to work just fine. So there is no bug pending to be handled from my side.
2. bug 2 deserves to be tracked separately.

**Comment by funderburkjim** [comment]
I'm only barely aware of what you're doing.  Doesn't matter.  Looks like you are enjoying!

**Comment by drdhaval2785** [comment]
Hi Jim,
Sorry for not specifying what I am doing and why I am doing precisely. Let me try.

# Problem statement

There are at least two downstream applications that I am aware which use Cologne data. [stardict-dictionary-updater](https://play.google.com/store/apps/details?id=sanskritcode.sanskritdictionaryupdater) and https://ashtadhyayi.com/kosha/

They usually were having Cologne data taken at some specified time. So, the problem statement was to keep their data in sync with changes which we are making at Cologne.

# Implementations

1. stardict-dictionary-updater uses .babylon files as their base filed to generate stardict file. https://github.com/sanskrit-lexicon/cologne-stardict is the place where I generate new babylon files based on XXX.txt in csl-orig repository via XXX.xml file. I then put these babylon files in https://github.com/indic-dict/stardict-sanskrit. From there, they have a continuous integration in place, which automatically generates stardict files and launch the revised version through their updater app.
2. ashtadhyayi.com uses json files as their base. I am updating json files in https://github.com/sanskrit-lexicon/csl-json repository.  They have not yet setup a continuous integration. So, they will have to pull the csl-json repository to get benefit of our data.
3. So, once our babylon and json files are updated by a cronjob, they can use them for their applications. 
4. I have completed the automation and creating cronjob. Whenever there is a change in csl-orig and I boot my laptop, the whole process wouls be automatically done, without any human intervention.

**Comment by drdhaval2785** [comment]
# A concrete example

1. Recently Jim updated ben.txt in csl-orig repository via commit https://github.com/sanskrit-lexicon/csl-orig/commit/bb89befb590153dedf9c9568d4063d2ce3d05acf 
2. I reopened my laptop, which ran some jobs at the reboot via cronjob at this [script](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/redo_xampp_selective.sh).
3. babylon file ben.babylon was updated at cologne-stardict repository automatically via commit https://github.com/sanskrit-lexicon/cologne-stardict/commit/138383c55b6685737ae61dd809a34548c48e5229 .
4. babylon file was transferred to indic-dict/stardict-sanskrit repository via commit https://github.com/indic-dict/stardict-sanskrit/commit/545df3260c250ec99a5422c8f42fe2f759fb5be9 .
5. The Continuous Integration (CI) set up on that repository regenerated dictionaries via this build - https://github.com/indic-dict/stardict-sanskrit/runs/3366563047 , which resulted in new tar files at https://github.com/indic-dict/stardict-sanskrit/commit/a55324f1fcf7ba3f593bba941b563600c51a19e4 and their application started showing new version of benfey https://github.com/indic-dict/stardict-sanskrit/raw/gh-pages/sa-head/en-entries/tars/benfey__2021-08-18_23-33-53Z__1MB.tar.gz  
6. For ashtadhyayi.com, csl-json was updated with latest benfey file via commit https://github.com/sanskrit-lexicon/csl-json/commit/b50a3adece29a09b01f268b2f58adc48dc17028e .

This whole process has been made idempotent, so only the changed file between commits is processed, and no other dictionary is touched, which results in faster updation.

**Comment by drdhaval2785** [comment]
The updated benfey dictionary is available to all users. See attached creenshot, showing benfey with timestamp of today.


![Screenshot_20210819-053005_Stardict Dictionary Updater](https://user-images.githubusercontent.com/5755132/129987081-184759fc-2d9b-4f49-ae0f-63659f1181e7.jpg)

**Comment by drdhaval2785** [comment]
The commit by Jim changed bettle to beetle in headword tElapAyin. The same is available to me once I updated my benfey dictionary by stardict-dictionary-updater. 
![Screenshot_20210819-053851_EBDic](https://user-images.githubusercontent.com/5755132/129987840-e2be7595-72bf-435d-8210-2d363f161ae0.jpg)
