### ISSUE TITLE
digitization update workflow

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#3]
This is to document usage of csl-orig.

## Initialization 
This need be done only once on some local machine
* preparation
  ```
   mkdir csl-orig
   # by some means, create .gitignore
   cd csl-orig
   mkdir v00
   cd v00
   mkdir csl-data
   # by some means, get the `updateDistinctData.sh` script, and put in csl-orig/v00
  ```
* Assuming still in csl-orig/v00,
  `sh v00/updateDistinctData.sh` # this will take a while

Now, csl-orig/v00/csl-data is populated with 
* XXXScan/2020/orig/xxx.txt
*  XXXScan/2020/orig/hwextra/xxx_hwextra.txt  ## see separate note questioning this

**Comment by funderburkjim** [comment]
## Origin repository
The local computer version of csl-orig repository has been initialized.
Next, it needs to be put some place in the cloud.  
Current origin repository is within sanskrit-lexicon project at Github.

**Comment by funderburkjim** [comment]
## Cologne copy csl-orig
As mentioned in #1, there will need to be a copy at Cologne. 
Let's assume it is in `scans/csl-orig` .
To get it here, assuming the origin is at Github as above,
we could : 
```
cd scans
git clone git@github.com:sanskrit-lexicon/csl-orig.git
```

**Comment by funderburkjim** [comment]
## Updating digitizations
Assume the above setup, with a local copy, a 'cloud' copy, and a Cologne copy, with the cloud copy being the csl-repository origin.

Suppose we want to change the digitization of a particular dictionary, with code xxx.
* in local csl-orig, make changes to v00/csl-data/XXXScan/2020/orig/xxx.txt.
   * This could be done manually (by opening xxx.txt in a text editor), and making changes manually.
      After each manual change, 
      * the xxx.txt file should be saved
      * git add xxx.txt  # stage the change
      * git commit -m "A uniformly structured commit message"
        See https://github.com/sanskrit-lexicon/Cologne/issues/280 for format of commit message
   * This could be done programmatically, by running some program that changes xxx.txt.  In most cases we should 
      * do programmatic changes in a subfolder (suggested naming convention)
      `csl-data/XXXScan/2020/orig/correctionwork/yyyymmdd`
      * make a 'redo.sh' file in the subfolder so the work is reproducible. 
      * make a readme file in the subfolder that describes what changes the 'redo.sh' makes
      * change .gitignore if needed, so only *required* files in subfolder are saved by git.
      * Of course, `git add xxx.txt` and `git commit -m "good message, maybe referencing subfolder`
* git push origin master  # to push the changes to repository origin
* On Cologne server,
   * cd scans/csl-orig
   * git pull origin master
   * copy v00/XXXScan/2020/orig/xxx.txt ../XXXScan/2020/orig/

## post-update (TODO)
These steps have yet to be finalized.
Probably they will be done in scans/XXXScan/2020/pywork by a script which will do
`redo_hw.sh`, `redo_xml.sh`,  and some other steps to update the scans/XXXScan/2020/web/ as needed (such as for web/sqlite/xxx.sqlite, and web/webtc2/query_dump.txt).

**Comment by funderburkjim** [comment]
## Cologne post-update (after change to csl-orig)
These instructions will do the necessary work on the Cologne server.
```
cd scans/csl-pywork/v02
#  for each dictionary whose digitization changed:  Let 'xxx' be the dictionary code.
# 1. Get the command to update dictionary 'xxx' at Cologne:
grep ' xxx ' redo_cologne_all.sh
# The result will be 'sh generate_dict.sh xxx  ../../XXXScan/2020/'
# 2. Do the update for xxx
#  For example if the dictionary code is 'acc', execute command:
sh generate_dict.sh acc  ../../ACCScan/2020/
# That's it.
```

**Comment by funderburkjim** [comment]
## XAMPP or Ubuntu post-update (after change to csl-orig)

Recall file-system assumptions.   You have a 'cologne' directory under
* xampp/htdocs (for XAMPP server on Windows 10)
* /var/www/html (for Ubuntu)

In the cologne directory, you have cloned versions of csl-orig, csl-pywork, and csl-websanlexicon 
repositories.

```
# Pull current version of csl-orig repository.
# cd to your csl-orig repository
git pull origin master  # bring in the changes to the digitizations
# Move into the version 2 subdirectory of pywork
cd ../csl-pywork/v02
# For each dictionary of interest: Let 'xxx' be the dictionary code.
# 1. Get the command to update dictionary 'xxx' on your xampp or ubuntu server:
grep ' xxx ' redo_xampp_all.sh
# The result will be 'sh generate_dict.sh xxx  ../../x'
# 2. Do the update for xxx
#  For example if the dictionary code is 'acc', execute command:
sh generate_dict.sh acc  ../../acc
# Your updated dictionary will now be in subdirectory 'xxx' of directory 'cologne'.
#  e.g., in /c/xampp/htdocs/cologne/xxx for xampp or
#  in /var/www/html/cologne/xxx for Ubuntu.
# The displays will be available at url:
#  http://localhost/cologne/acc/web/   (for xampp)
#  http://your-domain.com/cologne/acc/web/  (for Ubuntu)

```

**Comment by drdhaval2785** [comment]
System has matured now.
