### ISSUE TITLE
mw:p= 215,2

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#31]
date:	09/01/2019 09:11:01
dict:	mw
Lnum:	p= 215,2
hw:	उपे
old:	1. उपे (उप-√ इ) P. -एति
new:	1. उपे (उप-√ इ) P. -ऐति
comm:	It seems to be an error in the printed edition. Cf. परमं साम्यमुपैति Muṇḍ. Up.3.1.3. योगी परं स्थानमुपैति चाद्यम् Bg.8.28 (apud Apte). It could be that this is only MW’s method of presentation, and that the Sandhi should be understood and supplied by the reader (in this case उप+एति=उपैति), but this would be misleading and confusing for the user. MW itself adopts a different method in an analogous case: [p= 56,2] अपे (√ इ) P. Ā. अपैति (...).
email:	zaaf2@hotmail.com

**Comment by drdhaval2785** [comment]
@zaaf2 Do you want this change to be made? Or any second thoughts?

**Comment by Andhrabharati** [comment]
I guess it should be left as in print, it being the MW style of indicating sandhi split constituents (in their basic forms).

Looked for the cases of ऐति in MW data, and got 

case-1:  anūd-e (-ā-√i) cl. 2. P. anūd-**aiti**, to rise or come up after, ŚBr.  &c. [ID=7725]

case-2: anv-e (ā-√i) cl. 2. P. **-aiti**, to come after, to follow as an adherent or attendant, RV. i, 161, 3, &c. [ID=8927]

case-3: 1. upe (upa-√i) P. **-aiti**, to go or come or step near, approach, betake one's self to, arrive at, meet with, turn towards, RV. ; AV. ; TS. ; ŚBr. ; MBh. ; Śak.  &c.; 

The is the entry in discussion and seemingly the correction has already been done, which I guess should be reverted back to the print form.
MW book has took utmost possible care to have consistency in style throughout, and we should not go against this style.
[**A reader is presumed to keep in mind the style or rules followed in any work that he is referring to.**]

case-4: 2. upe (upa-ā-√i) P. **-eti**, to approach, come near or towards, RV. ; AV. ; ŚBr. ; 
`----------`
> MW itself adopts a different method in an analogous case: [p= 56,2] अपे (√ इ) P. Ā. अपैति (...).

ape (√i) P. Ā. apaiti, apāyati (impf. Ā. apāyata, RV. x, 72, 6) to go away, withdraw, retire, run away, escape; 

Here MW chose to give the no split form, and as such the composite form अपैति is there.

**Comment by zaaf2** [comment]
I agree with Andhrabharati

**Comment by Andhrabharati** [comment]
time to close this, @drdhaval2785 ?

**Comment by drdhaval2785** [comment]
Leave it as it is. Closing.
