### ISSUE TITLE
mw:avikā

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#333]
date:	07/05/2020 22:24:40
dict:	mw
Lnum:	avikā
hw:	18629
old:	(avikā)
new:	(avíkā)
comm:	Typo

**Comment by funderburkjim** [comment]
User has very sharp eyes!

![image](https://user-images.githubusercontent.com/6393033/89834462-e24f9180-db30-11ea-85ea-ae692155f53c.png)

**Comment by gasyoun** [comment]
> User has very sharp eyes!

Even I can see it :)
