### ISSUE TITLE
SKD: pUrbba -> pUrvva

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#465]
Peter noticed under L=41108 that pUrbbaM should change to pUrvvaM.

I decided to change ALL pUrbba to pUrvva.   This seems safe to me.

About 3700 instances changed.

**Comment by funderburkjim** [comment]
Also changed:  
* pUrbbA to pUrvvA  (602)
* pUrbbo to pUrvvo (249)
* pUrbbe to pUrvve (205)
* pUrbb to pUrvv  (the rest of them) (118)

**Comment by gasyoun** [comment]
> 3700 instances

Big one.
