### ISSUE TITLE
VCP:  L=44490, zaqaBijYa

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#469]
Submitted by @Andhrabharati 
वाचस्पत्यम् lists the six (in p. 5166) as- 
1. दिव्यं चक्षुःश्रोत्रं 
2. परचित्तज्ञानं (book has परिचित्तज्ञानं) 
3. पूर्वनिवासानुस्मृतिः 
4. आत्मज्ञानम् (Cologne has आत्मज्ञानभ्) 
5. वियद्गतिः 
6. कायव्यूहसिद्धि (Cologne has कायव्यूहमिद्धि)

Changes (SLP1):
```
paricittajYAnaM -> paracittajYAnaM  (print change)
mAtmajYAnaB -> AtmajYAnam (typo)
kAyavyUhamidDi -> kAyavyUhasidDi
```

**Comment by funderburkjim** [comment]
Corrected, and posted the print change to [vcp_printchange.txt](https://github.com/sanskrit-lexicon/csl-corrections/blob/master/dictionaries/vcp/vcp_printchange.txt).

**Comment by gasyoun** [comment]
> आत्मज्ञानम् (Cologne has आत्मज्ञानभ्)

So words ending on `bh` are possible errors.

**Comment by drdhaval2785** [comment]
Nope. अनुष्टुभ् is a valid word. ककुभ् is a valid word.

**Comment by Andhrabharati** [comment]
My long-term wish is to "look" into this work as well, the way I did at MW99. (I did started it alingwith MW99 in 2016, but that didn't go for long, as had to switch to some of AB's "scheduled" works; hope I would be reviving this task sometime in near future.)

Personally, I regard this as a better compilation, in comparision with SKD.

**Comment by funderburkjim** [comment]
Some previous work has been done comparing the Tirupati and Cologne versions of Vacaspatyam.

This is in the VCP repository, part of comparison is https://github.com/sanskrit-lexicon/VCP/tree/master/vac-vcp-cmp1 .

and also several other places in that repository.

**Comment by Andhrabharati** [comment]
Took a small break to look into the VCP text at Koeln.

Just started with vcp-meta2 file contents,
and here is the result-
[vcp-meta2 (AB response).txt](https://github.com/sanskrit-lexicon/csl-orig/files/6115039/vcp-meta2.AB.response.txt)

Then did a comparison of a portion one of the entries in this file,
and the result is-
[ग्रहगोचर_Cologne.txt](https://github.com/sanskrit-lexicon/csl-orig/files/6115045/_Cologne.txt)
[ग्रहगोचर_AB.txt](https://github.com/sanskrit-lexicon/csl-orig/files/6115046/_AB.txt)

**"Just about 60 lines out of 200 lines are done correctly in Koeln text."**

Though the text throughout may not be this bad, it sure is not up to "any" mark; and needs a thorough **revamping**.
Even a graduate level person (knowing Sanskrit basics) could get much of the text correct, NO NEED for any expertise.

Kudos to the typists who have brought the text to this level- it is not at all an easy task to do this voluminous work, esp. with the illegible scans/prints floating around. The blame purely goes to the reviewers/editors, at both Tirupati and Cologne centers.

Of course, the filling up of the "unreadable text" is not possible by everyone.
[Even I could do so **as I am in possession of a FAR FAR FAR better scan set**, compared to the easily accessible RSS, Chowkhamba and Cologne scans.]

**Comment by Andhrabharati** [comment]
And finally I should say that my acquiring a little bit of knowledge in all traditional (Indian) subjects has proved quite helpful here!

**Comment by gasyoun** [comment]
> TPT has better text at many places.

Like? I believed after our comparison that @funderburkjim made we become stronger that Tirupati.

> Cologne has missed the corrections interspersed in various pages of the print volumes.

Not even missed - not aware of them. Where to look for them?

> TPT has marked the data with some tags, like Cologne did in its MW99 data; Cologne did not do much of tagging.

Not even tried to. What tags do they use?

**Comment by funderburkjim** [comment]
> FAR FAR FAR better scan set

Better scans would be a big help.

If possible, would be good to replace our current scans  with better ones.

Perhaps you can supply with a sample, so we can determine the comparability?

**Comment by Andhrabharati** [comment]
Though it was a simpler task for me to just attach the scan pages concerned, I took "inspiration" from the way @funderburkjim took time to "create" a webpage for the "rev" task in MW99- and picked up only the relevant lines from those pages.

And the results are-

[scan portions for the meta2 unreadable line observations.xlsx](https://github.com/sanskrit-lexicon/csl-orig/files/6124508/scan.portions.for.the.meta2.unreadable.line.observations.xlsx)

[scan portions for the meta2 unreadable line observations.pdf](https://github.com/sanskrit-lexicon/csl-orig/files/6124501/scan.portions.for.the.meta2.unreadable.line.observations.pdf)

[scan portions for the meta2 unreadable line observations.zip](https://github.com/sanskrit-lexicon/csl-orig/files/6124499/scan.portions.for.the.meta2.unreadable.line.observations.zip)
[This is a .mht (single web page) created by Excel and zipped, as Github did not allow the file type to be attached.]

**Looks it is my "experience" that played a bigger role than the scan quality, in resolving these portions.**
But still guess the scans are better, as they gave scope to clear things easily.

**Comment by Andhrabharati** [comment]
> > TPT has marked the data with some tags, like Cologne did in its MW99 data; Cologne did not do much of tagging.
> 
> Not even tried to. What tags do they use?

@gasyoun, it may be of more interest to you!

They've marked all the धातु, व्युत्पत्ति, ... portions, in addition to some more of other categories.

**Comment by Andhrabharati** [comment]
> > FAR FAR FAR better scan set
> 
> Better scans would be a big help.

> Where to look for them @Andhrabharati ?

Nothing secret here!

It's the 22 volume set originally published (as ~240 pp each, except the last volume which is ~400 pp), which were then sold as combined bindings after few volumes are completed; and the Poona Dictionary is getting sold now in the same way.
[Marcis may note the point for his "Chronology of Sanskrit Lexicons"!]

As it is "convenient", later (re)prints [after few decades] took only the combined bindings as the base, and we know the end-result.

These originals can be got from both archive.org and Google Books.

**Comment by Andhrabharati** [comment]
> If possible, would be good to replace our current scans with better ones.

Never do so.
Instead of replacing, keep both the two sets as alternate sources.

At very few places, seen that the scanned 22 volume set has some "issues" (blurred/cut/...) and the later prints are to be referred to to get them correctly.

**Comment by Andhrabharati** [comment]
Here is the list, the way I renamed them for easier reference (to go to a particular word or page)-

![image](https://user-images.githubusercontent.com/75209130/110826572-384d0900-82bb-11eb-9287-c9c42bd5512e.png)

**Comment by Andhrabharati** [comment]
History has it that he was "asked" (by the Government) to "compromise" and curtail the copious citations that he has collected to add at the respective entries, from the letter pa onwards.

Otherwise, the work would've easily grown into another 10-15 volumes more.

**Comment by gasyoun** [comment]
> "Chronology of Sanskrit Lexicons"

Was unaware that it was printed in parts, because I have seen in BORI only later reprints.

> ~240 pp each

Similar to the 200 pages standard Deccan college has now.

> from the letter pa onwards.

Yeah, out of money.

> would've easily grown into another 10-15 volumes more.

One can actually how many volumes would it be.

**Comment by funderburkjim** [comment]
> These originals can be got from both archive.org and google.books

Can you provide a sample link to each, so I'll know exactly what you are looking at?

**Comment by Andhrabharati** [comment]
you mean to give the pieces from the latter 6-volume set as well, in addition to the 22-volume "lines" that I gave?

aren't the page & line ref.s in the file sufficient?

**Comment by Andhrabharati** [comment]
these are available at scribd as well, posted by the user sktkoshas.

**Comment by Andhrabharati** [comment]
you know what?

they are all the ones that became the 22-volume set finally.

the total volume (estimated) number  just went on changing, as the printing progressed.

**Comment by Andhrabharati** [comment]
Here is the list of actual titles of the volumes-

![image](https://user-images.githubusercontent.com/75209130/110891524-29487400-8318-11eb-9ae2-35f1f5dd5bd5.png)

**Comment by Andhrabharati** [comment]
> 
> > ~240 pp each
> 
> Similar to the 200 pages standard Deccan college has now.
> 

I guess 240 has a relation to printer's form which gets cut to various sizes- quarto, octo, ...

In this case it is 8, so 30 forms every 6 months was the plan, as mentioned in the front pages.

I take 200 of Poona as just a random rounded-off number.

**Comment by Andhrabharati** [comment]
> > reviewers/editors, at both Tirupati and Cologne centers, for not paying required attention.
> 
> None. 

Does this mean that no reviewing took place at Cologne?

This is what I see at https://sanskritlibrary.org/nehDFG2009.html-

> In addition to the NEH grant, by virtue of his current position in a Chaire Internationale de Recherche Blaise Pascal, the project director contracted IIT Bombay to engage two post-doctoral Sanskrit researchers to assist in editing lexical resources and correlating their headwords.
> `... ... ... `
>
> Sivaja Nair, Post-doctoral Research Associate (IITB)
> Sampada Savardekar, Post-doctoral Research Associate (IITB)

And this one in the file vcpheader.xml-
   ```> <editionStmt>
>     <edition>xml version, <date when="2013">2013</date></edition>
>     <respStmt>
>      <resp>Correction of misordered headwords and unclear characters</resp>
>      <name>Dr. Sampada Savardekar Thomas</name>
>     </respStmt>
>    </editionStmt>
```

So my above remark gets addressed to Thomas Malten and Sampada Savardekar.

**They should've taken enough time to bring the text to a reasonably good shape, instead of "closing" the work in a hurry.**

And if necessary, Peter Scharf should've got the project "extended"; as I understand, he has enough strength and "hold" in the funding agencies to do so.

**Sorry if I've crossed my limits, but I can't hide my feelings unexpressed.**

**Comment by Andhrabharati** [comment]
I just hope that in the bulk of these remarks, the original ones on the meta2 entries do not get out of attention.

Another particular point as seen in those entries-- in the Prakrit texts cited, Cologne slp1 notation has "missed" the adjacent dual vowels which do not make a sandhi as in Sanskrit. Two such were seen in these 46 listed. (In MW99, such cases were marked with umlaut.)

**Comment by gasyoun** [comment]
> In MW99, such cases were marked with umlaut

Umlaut stands for list of vedic words with hiatus in MW99 for Vedic words, a list of around 100 words.

> And if necessary, Peter Scharf should've got the project "extended"

Seems that Peter had a different opinion on the readiness of the files. Anyway, I agree with you, they contain a level of dirt that should not be left as is and you can fill the gap now, 8 years after. To make them seems to be quicker than to clean them. To add additional markup - maybe even longer.

**Comment by Andhrabharati** [comment]
> 
>     In MW99, such cases were marked with umlaut
> Umlaut stands for list of vedic words with hiatus in MW99 for Vedic words, a list of around 100 words.

@gasyoun 

I meant the double-dotted ones - aï, aü (which are termed diaresis).
I see only about 55 of them in MW99- belonging to both Vedic and Prakrit words.
**Did I miss the rest of the 100 that you are saying?**

**Comment by gasyoun** [comment]
> I see only about 55 of them in MW99- belonging to both Vedic and Prakrit words.
Give the list here.

See https://github.com/sanskrit-lexicon/COLOGNE/issues/260
and https://github.com/sanskrit-lexicon/CORRECTIONS/issues/10

**Comment by funderburkjim** [comment]
On scribd, sktkoshas  I could not find volumes  I, III, IV, VI.  Other volumes found.

**Comment by funderburkjim** [comment]
Found volumes I, III, IV and VI at archive.org.

**Comment by Andhrabharati** [comment]
Here are the links-

Vol.1
https://archive.org/details/vacaspatyaacomprehensivesanscritdictionaryintenpartspartiaap_41_i
https://www.scribd.com/doc/106533946/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-I-a-AP-Calcutta-1873-600dpi-Lossless

Vol.3
https://archive.org/details/vacaspatyaacomprehensivesanscritdictionaryintenpartspartiiiashuaan_751_N
https://www.scribd.com/document/106535560/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-III-Ashu-Aan-Calcutta-1873-600dpi-Lossless

Vol.4
https://archive.org/details/vacaspatyaacomprehensivesanscritdictionaryintenpartspartivaanindriya_140_
https://www.scribd.com/document/106536262/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-IV-Aan-Indriya-Calcutta-1874-600dpi-Lossless

Vol.6
https://archive.org/details/vacaspatyaacomprehensivesanscritdictionaryintenpartspartviupartu_369_F
https://www.scribd.com/document/106537943/Vacaspatya-A-Comprehensive-Sanscrit-Dictionary-in-Ten-Parts-Part-VI-Upa-Rtu-Calcutta-1875-600dpi-Lossless
