### ISSUE TITLE
PWG:52860, budDagayA

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#472]
submitted by email

dict: PWG
L=52860
hw=budDagayA
old: Luddhisten
new: Buddhisten

print smudge

![IMG_0036](https://user-images.githubusercontent.com/6393033/111050690-1f0f9e00-841c-11eb-97e7-8f6feec655cf.jpg)

**Comment by funderburkjim** [comment]
Correction made.

**Comment by gasyoun** [comment]
> Luddhisten

A o vs O content analysis would weed out such cases. But we have not tried to apply it outside headwords.
