### ISSUE TITLE
PWG: <ls>H. Ś. -> <ls>H. ś.

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#520]
This as part of solution of problem mentioned [here](https://github.com/sanskrit-lexicon/PWG/issues/33#issuecomment-821511429).

In the pwg.txt digitization, there are 3 instances of an upper-case form `<ls>H. Ś.`
whereas there are 1286 instances with the lower-case form `<ls>H. ś.`.
Examination of the scan for the 3 instances suggests that the lower-case form is proper.
So this change was made.

**Comment by gasyoun** [comment]
> Examination of the scan for the 3 instances suggests that the lower-case form is proper.

Agree.
