### ISSUE TITLE
armhxmlheader

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#522]
@drdhaval2785  You need to fill out [armhheader.xml](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/armh/armhheader.xml).

Suggest you use [lanheader.xml](https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/lan/lanheader.xml) as example.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-orig/commit/7eaf04ae8d6f88bd1139a50fa2218de009c8acdb added this missing header file.
