### ISSUE TITLE
VCP: 348, agnizvAtta

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#601]
Correct markup introduced at commit 'VAC VCP line 2500'.  See https://github.com/sanskrit-lexicon/csl-orig/commits/master/v02/vcp/vcp.txt.

Unknown xml markup was introduced in 'VAC VCP line 2500' changes.
This caused failure in reconstructing the display for VCP.
This problem is corrected now.

@drdhaval2785   You may wish to use xmlvalidate.py ([see](https://github.com/sanskrit-lexicon/COLOGNE/tree/master/enhancements/code)) in local installation to check for validity of generated xml.
The workflow is (for vcp)
* make changes in csl-orig/v02/vcp.txt
* in csl-pywork/v02,  
  * `sh generate_dict.sh vcp  ../../vcp`
  * `python ../../xmlvalidate.py ../../vcp/pywork/vcp.xml ../../vcp/pywork/vcp.dtd`
     * if xml validates, 'ok' is printed.
     * otherwise, an error message shows line number of vcp.xml.
     
I use this frequently to be sure invalid markup is not accidentally introduced into the digitizations.

**Comment by drdhaval2785** [comment]
I got it. I would also regenerate vcp locally, to be sure that mass scale changes do not break any markup. Thank you for the tip.
