### ISSUE TITLE
GST tag for script / language

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#610]
```
	Line 6389:	<div n="lb">from the Persian. {??}. E. {#अञ्ज्,#} aff. {#ईरन्#}.
		<div n="lb">from the Persian انجیر. E. {#अञ्ज्,#} aff. {#ईरन्#}.
		%% This might have to be appropriately tagged for the script.
```

I do not know whether we should tag it like `<lang n="persian">انجیر</lang>` 
What is the language code for Persian, @funderburkjim ?

**Comment by Andhrabharati** [comment]
This is how it is seen in MW-
<lang script="Arabic" n="Persian">شاه</lang>

**Comment by funderburkjim** [comment]
For discussion of the 'script' attribute, see discussion https://github.com/sanskrit-lexicon/COLOGNE/issues/68
