### ISSUE TITLE
GST author's book advertisement

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#611]
```
Lines 45468-45655 are part of publisher's advertisement and should be deleted from the file.
```

Ref - https://github.com/sanskrit-lexicon/CORRECTIONS/issues/92#issuecomment-913174476

**Comment by funderburkjim** [comment]
I see no harm in removing the lines from gst.txt

Should the removed lines be saved in a file?  Maybe in csl-orig/v02/gst/gst_something.txt   (not sure of file name).

**Comment by drdhaval2785** [comment]
gst_advertisement.txt seems a good enough name to me.

**Comment by funderburkjim** [comment]
to me, too.
