### ISSUE TITLE
VEI question 

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#614]
```
	Line 1461:	<div n="lb"/>{??} 342, 500.</F>
		<div n="lb"/>, 342, 500.</F>
		%% should this comma have something before it (nothing is in the print page!) or is it there by error?
```

**Comment by Andhrabharati** [comment]
@drdhaval2785 

this should not be at SCH.

I noted it in VEI.

**Comment by Andhrabharati** [comment]
This is what I see in VEI p.24
![image](https://user-images.githubusercontent.com/75209130/132223648-1f0fedba-ce5c-4274-b8ba-1b97d64650ea.png)

@gasyoun 
This is what prompted me to look for Ludwig's Translation, and then acquired a small know-how about him!

**Comment by Andhrabharati** [comment]
Had looked at Ludwig's Translation volumes and found that Vol. 3 is being referred to here!

![image](https://github.com/user-attachments/assets/eb6c5365-c1cf-4757-b069-dd8fdbfab07d)

![image](https://github.com/user-attachments/assets/3e733cc2-69a2-47c7-ba4a-2d83ab0b16e0)

With this, we can add '3' at VEI p.24 FN and close this issue.

@drdhaval2785/ @funderburkjim,
any chance for your handling this now?

**Comment by funderburkjim** [comment]
@Andhrabharati 
I don't see where the '3' is to be added.  
Below is the apacit entry from vei.txt.
Please specify exactly what is to change. Is this a print change?
```
<L>82<pc>1-024<k1>apacit<k2>apacit
{@Apa-cit.@}¦ — This word occurs several times in the Atharvaveda.<sup>1</sup>
It is held by Roth,<sup>2</sup> Zimmer,<sup>3</sup> and others to denote an insect
whose sting produced swellings, etc. ({%glau%}). But Bloomfield<sup>4</sup>
shows that the disease, scrofulous swellings, is what is really
meant, as is shown by the rendering ({%gaṇḍa-mālā,%} ‘inflammation
of the glands of the neck’) of Keśava and Sāyaṇa, and by the
parallelism of the later disease, {%apacī,%} the derivation being from
{%apa%} and {%ci,%} ‘to pick off.’
<F>1) vi. 25, 1; 83, 1; vii. 75, 1; 77, 1.</F>
<F>2) St. Petersburg Dictionary, {%s.v.%}</F>
<F>3) {%Altindisches Leben,%} 97. So also
Ludwig, Translation of the Rigveda,
, 342, 500.</F>
<F>4) {%American Journal of Philology,%} 11,
320 {%et seq.; Hymns of the Atharvaveda,%}
503, 504. {%Cf.%} Jolly, {%Medicin,%} 89;
Whitney, Translation of the Athar-
vaveda, 343.</F>
<LEND>
```

**Comment by Andhrabharati** [comment]
@funderburkjim 

It is at beginning of last line of FN-3, i.e., before "342, 500".

You may go through the posts above, to know the context, and then clise the issue too.

Yes, it can be considered as a print_change!

**Comment by funderburkjim** [comment]
Closing this issue.
