### ISSUE TITLE
GRA:  7, aMsa

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#616]
Correct unbalanced `<ab>` tag:
```
OLD: 
<lang n="greek">ὦμος</lang> umerus, <ab>go.<ab> amsa (<ab>Cu.</ab> 487) erwiesen.
NEW:
<lang n="greek">ὦμος</lang> umerus, <ab>go.</ab> amsa (<ab>Cu.</ab> 487) erwiesen.
```

Remember xmlvalidate.py .

**Comment by funderburkjim** [comment]
Incidentally, what is the tooltip for 'go.'  in GRA?   

In order for tooltip to appear for 'go.' in GRA displays,
also https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/gra/pywork/graab/graab_input.txt requires updating,
and then pywork/v02  script for GRA rerun.

**Comment by Andhrabharati** [comment]
go. = gothic

**Comment by Andhrabharati** [comment]
@drdhaval2785 may pl. update this.

**Comment by funderburkjim** [comment]
Abbreviation 'go.' now installed:

![image](https://user-images.githubusercontent.com/6393033/132956337-54a03a02-70d2-420f-9f04-91d3a4d167b9.png)

**Comment by funderburkjim** [comment]
Cu. above has '?' for tooltip.
These are the GRA abbreviations with a '?'

```
4 matches for "[?]" in buffer: graab_input.txt
      8:adv.	<id>adv.</id> <disp>adverbial? - adverbial</disp>
     15:Denom.	<id>Denom.</id> <disp>Denominativ? - denominative</disp>
     63:Iv.	<id>Iv.</id> <disp>?</disp>
     69:Cu.	<id>Cu.</id> <disp>?</disp>
```

**Comment by Andhrabharati** [comment]
> Cu. above has '?' for tooltip.

![image](https://user-images.githubusercontent.com/75209130/132957244-b89d02a5-a46b-4b3e-95f8-40bdc3c6f24f.png)

[The etymology could not be missing, as it is often central to determining the meaning of a lemma. However, I kept the etymology as short as possible by referencing Curtius, Grundzüge der griechischen Etymologie (Cu.), Fick, Vergleichendes Wörterbuch der indogermanischen Sprachen 1870 (Fi.) , Kuhn, Zeitschrift für vergleichende Sprachforschung (Ku.), Böhtlingk und Roth, Sanskrit-Wörterbuch (BR.), Benfey, Glossar zum Sāma-Veda (Be. SV. gl.), as well as occassionally referencing other works. Compounds are indicated by a hyphen seperating the parts of the compound.]

Would this help you, @funderburkjim?

**Comment by Andhrabharati** [comment]
Incidentally this piece of Intro text talks about few more abbr.s- Fi., Ku., BR., Be. that are not in graab_input.txt!!

**Comment by funderburkjim** [comment]
It helps with Cu. : Tooltip = Curtius, Grundzüge der griechischen Etymologie 

I also see 
* 70 unmarked 'Fi.' 
* 97 unmarked 'Ku.'
* 298 unmarked 'BR.'
* Be. SV. gl. less clear  (first 2 clear -- will add to abbreviations.  Not sure of last 2
   * 2 'Be. Sv. gl.'
   * 2 'Be. Sv. gloss.'
   * 1 Be. vollst. Gramm.  (headword DizaRA)
   * 1 (Be.)  (headword yaTA, p. 1083)
 
Will add those.

'Iv.' occurs 130 times.  e.g. under
```
<L>1211<pc>0136<k1>aS<k2>aS<h>2
<L>3428<pc>0479<k1>jar<k2>jar<h>2
```
May be a grammar abbreviation?

**Comment by Andhrabharati** [comment]
Be. is Benfey!
And he wrote a Grammar book as well, A Practical Grammar of the Sanskrit Language which is the 4th one.

I am glad that Benfey is coming to limelight now!
Wonder why and how @gasyoun takes him of no importance.

**Comment by Andhrabharati** [comment]
> 
> 'Iv.' occurs 130 times. e.g. under
> May be a grammar abbreviation?

Seems it is eqvt. for English p.p.

**Comment by Andhrabharati** [comment]
And I see that this GRA also has quite a few undocumented abbr.s yet to be enlisted in gra_ab.

**Comment by Andhrabharati** [comment]
> 
> 
> > 'Iv.' occurs 130 times. e.g. under
> > May be a grammar abbreviation?
> 
> Seems it is eqvt. for English p.p.

Look at jar entry-

![image](https://user-images.githubusercontent.com/75209130/132959326-d9566e64-eb80-444d-bff4-49cae94f9bb6.png)

MW is helpful here!

![image](https://user-images.githubusercontent.com/75209130/132959275-e6220c42-b6bc-4cba-adde-956c18096057.png)

So we can take that (GRA) Iv. is Imperative. (courtesy MW99).

**Comment by funderburkjim** [comment]
p.p = perfect participle ?

looks more like a verb tense.  Maybe Imperative ?
```
({@jyut@})¦, {%leuchten%} [aus dyut]. Das <ab>Caus.</ab> jyotáya <lbinfo n="4"/>
 [2. <ab>s.</ab> <ab>Iv.</ab>], {%erleuchte%} im {AV. 7,16,1}. Davon jyótis.

jyotaya = 2nd singular imperative
```
cf [Huet](https://sanskrit.inria.fr/cgi-bin/SKT/sktlemmatizer.cgi?lex=SH&q=jyotaya&t=SL&c=Verb)

**Comment by funderburkjim** [comment]
Yep!  we come up with same result: Iv. = Imperative

**Comment by funderburkjim** [comment]
Markup to gra of the above abbreviations.

Tooltips for the abbreviations in graab_input.txt.

All done and installed.

**Comment by funderburkjim** [comment]
Regarding as yet unmarked abbreviations in GRA:

There are two parts:
* identify the abbreviations that need to be marked   (e.g. 'Fi.')
* identify the expansion (tooltip).

When work on this is done,  discussion in another issue (e.g. in GRA repository).

Closing this issue.
