### ISSUE TITLE
INM: 1306, BAnu hom 7

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#617]
Unbalanced {%%}  caused failure of xml validation
```
OLD:
<div n="lb">Bṛhadbhānu), 14184 {%(Bhānor bhāryā suprajā tu Bṛhadbhasā tu
<div n="lb">{%sūrya-jā),%} 14186 {%(tam Agniṃ Baladaṃ prāhuḥ prathamaṃ%}
NEW:
<div n="lb">Bṛhadbhānu), 14184 {%(Bhānor bhāryā suprajā tu Bṛhadbhasā tu%}    <<< add closing %}
<div n="lb">{%sūrya-jā),%} 14186 {%(tam Agniṃ Baladaṃ prāhuḥ prathamaṃ%}
```

@drdhaval2785 request:

When you change a dictionary csl-orig/v02/xxx/xxx.txt
please then, before committing csl-orig,  do the following in local csl-pywork/v02
a) sh generate_dict.sh xxx  ../../xxx
b) python ../../xmlvalidate.py ../../xxx/pywork/xxx.xml ../../xxx/pywork/xxx.dtd

If validation fails, find the mistake, correct in csl-orig/v02/xxx/xxx.txt, and redo a) and b).
Repeat until validation succeeds.

THEN it should be safe to commit csl-orig.

**Comment by funderburkjim** [comment]
I've made a simple script in csl-pywork/v02 called [xmlchk_xampp.sh](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/xmlchk_xampp.sh).

Use as `sh xmlchk_xampp.sh inm`  to check validity of inm.xml.
Assumes xmlvalidate.py is installed in the 'cologne' parent directory of 'csl-pywork'.

**Comment by drdhaval2785** [comment]
Fine. Will be more cautious in future. 
Validate first, push second.

**Comment by funderburkjim** [comment]
Thanks!
