### ISSUE TITLE
cae:19430 puMnAman

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#620]
```
<L>19430<pc>320<k1>puMnAman<k2>pu/MnAman<h>1
1 {#puM/nAman#}¦ <lex>a.</lex> having a masculine name.
<LEND>
```

The location of the accent in the k2 and text differs. One is after vowel. The other is after M.

**Comment by funderburkjim** [comment]
In discussion of font choice (https://github.com/sanskrit-lexicon/pwg/issues/5#issuecomment-894630351) , we decided, I think,  that accent should come after vowel.
