### ISSUE TITLE
cae:19431 punnAman

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#621]
```
<L>19431<pc>320<k1>puMnAman<k2>punnAman<h>2
2 {#punnAman#}¦ <lex>a.</lex> having the name {#pud#} (<ab>q.v.</ab>).
<LEND>
```
Note that k1 is puMnAman and the text and k2 have punnAman.
I am not sure what may be the source of this change in key1.
I always thought that key1 is a simplified form of key2, without accents and space etc.
 
If there is a difference in key1 and key2 as shown here in CAE, it would be a candidate for programmatic analysis to correct the errors.

**Comment by funderburkjim** [comment]
> I always thought that key1 is a simplified form of key2

That's the general principle.  Clearly the example above needed to be changed as was done.
