### ISSUE TITLE
BUR - compare Devanagari and IAST in headwords

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#626]
Reference - https://github.com/sanskrit-lexicon/COLOGNE/issues/180
```
ABIkzRa:ābhikṣṇa
iLaspati:iḷaspati
iLaspada:iḷaspada
ilA:iṭā
*IL:īḷ
upadA:abnormal
X:ḷī
karRAwa:karṇā2ta
kAvya uSanas:kāvya uśanas
catuHSAlA:catusśālā
catuHzazwi:catu(s)ṣaṣṭi
jihILire:jihīḷre
*Jarj:Jarj
duHsTiti:dusthtiti
nizIdAmi:niṣīddhāmi
niHSabda:nisśabda
niHSalAka:nisśalāka
niHSAsmi:nisśāsmi
niHSeza:nisśeṣa
niHSezayAmi:nisśeṣayāmi
niHSoDya:nisśodhya
niHSrayaRI:nisśrayaṇī
niHSreyasa:nisśreyasa
niHSvasimi:nisśvasimi
niHsaMSaya:nisaṃśaya
pratILe:pratīḷe
preLe:preḷe
virajyAmi:virajyami
SaWa:śạtha
SiSatsAmi:abnormal
```

**Comment by funderburkjim** [comment]
@drdhaval2785 
Please include the code which generated above list.

**Comment by drdhaval2785** [comment]
@funderburkjim 
With csl-pywork being used as mako template, I am a bit confused as to where should I put the code.
Earlier I used to put the code in CORRECTION repository or csl-correction repository.
Can you guide me where the code which are in exploratory phase can be put?

**Comment by drdhaval2785** [comment]
upadA 
Importance of abnormal tag.
Please see the image. Every other word has IAST along with Devanagari. upadA does not have any such thing.
May be considered a print error.
![image](https://user-images.githubusercontent.com/5755132/133457918-a619dc31-4847-4e08-a31c-ce9f4a4d85af.png)

**Comment by drdhaval2785** [comment]
![image](https://user-images.githubusercontent.com/5755132/133460789-60bee1f0-4574-4f63-956d-29acc57c3a17.png)

Kindly see the very slightly different letter (almost similar to s) used for visarga in BUR. It is a a source of constant errors in IAST encoding.
Corrected them to ḥ .

**Comment by drdhaval2785** [comment]
![image](https://user-images.githubusercontent.com/5755132/133461527-2caef7e3-b704-4443-9900-cc2e1b101621.png)

SiiSatsAmi is abnormal.
Every other desiderative has IAST. This is the odd one out.

**Comment by drdhaval2785** [comment]
upadA and SiSatsAmi - IAST added to make it congruent to every entry in the dictionary.

**Comment by drdhaval2785** [comment]
Rest corrections done.

**Comment by funderburkjim** [comment]
> where should exploratory code go?

My habit has been to put this either
* in subfolders of the XXX dictionary.
 So, in the case of BUR, this would be in subfolder of https://github.com/sanskrit-lexicon/BUR repository
* or in an attached file or two in the comment
   * e.g., if there are just one or two small pieces,  say blah.py and blah.txt,  I would 
      put in 'blah.py.txt' and 'blah.txt'   (by dragging files into an issue comment).  The 'blah.py.txt' is
      necessary since 'blah.py' can't be dragged into github.comment.

**Comment by funderburkjim** [comment]
another place would be in a Gist.
And then an issue comment linking to the Gist.
