### ISSUE TITLE
mw:200853  (shortlong display problem)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#639]
date:	07/08/2021 03:33:49
dict:	mw
Lnum:	200853
hw:	viśram
old:	śrāmyate, vy-aśrāmi, -śrāmyatām, -śrāmayati
new:	śrā̆myate, vy-aśrā̆mi, -śrā̆myatām, -śrā̆mayati
comm:	Typo

**Comment by funderburkjim** [comment]
![image](https://user-images.githubusercontent.com/6393033/135531751-99f331d1-a0bc-4f0d-9ba7-f6ebee66519f.png)

Current digitization uses 'shortlong' tag:
```
<div n="vp"/><ab>Pass.</ab> <s>-SrA<shortlong/>myate</s> (<ab>aor.</ab> <s>vy-aSrA<shortlong/>mi</s>, <ls>Vop.</ls>; <ab>esp.</ab> 3. <ab>sg.</ab> <ab>Impv.</ab>; <s>-SrA<shortlong/>myatAm</s>, ‘you may rest’, ‘enough of this’), <ls>Bhartṛ.</ls>; <ls>Ratnâv.</ls> :
<div n="to"/><ab>Caus.</ab> <s>-SrA<shortlong/>mayati</s>,
```
This is not an error in  the mw.txt digitization, but rather a limitation of the displays.

Our displays *ignore* the shortlong tag, because it is not known how to handle it in the various display transcodings.

Possibly the slp1_roman.xml transcoding file could readily be extended to handle shortlong.

**Comment by Andhrabharati** [comment]
how about rendering these as 'a(A)' etc.?

**Comment by Andhrabharati** [comment]
but in true sense of it, these denote dual forms; and could be made as sep. entries.

**Comment by Andhrabharati** [comment]
See for e.g., how BEN has redendered such dual forms (few samples)-

{#अङ्गुलि#} and {#अङ्गुली#}¦ {%aṅgulī̆%}
{#अटनि#} and {#अटनी#}¦ {%aṭanī̆%}
{#अतिसार#} and {#अतीसार#}¦ {%atī̆sāra%}
{#अधिकार#} and {#अधीकार#}¦ {%adhī̆kāra%}
{#अरणि#} and {#-णी#}¦ {%araṇī̆%}
{#अवनि#} and {#-नी#}¦ {%avanī̆%}
{#आवलि#} and {#ली#}¦ {%āvalī̆%}
{#ओषधि#} and {#धी#}¦ {%oṣadhī̆%}
{#औषधि#} and {#औषधी#}¦ {%auṣadhī̆ = oṣadhi%}
{#कटि#} and {#कटी#}¦ {%kaṭī̆%}
{#कर्त्तरि#} and {#री#}¦ {%karttarī̆%}
{#काकलि#} and {#काकली#}¦ {%kākalī̆%}
{#कोटि#} and {#टी#}¦ {%koṭī̆%}
{#क्षोणि#} and {#क्षोणी#}¦ {%kṣoṇī̆%}
{#तरि#} and {#तरी#}¦ {%tarī̆%}
{#तरि#} and {#तरी#}¦ {%tarī̆%}
{#दर्वि#} and {#दर्वी#}¦ {%darvī̆%}
{#दर्वि#} and {#दर्वी#}¦ {%darvī̆%}
{#धमनि#} and {#नी#}¦ {%dham + anī̆%}
{#नीवि#} and {#नीवी#}¦ {%nīvī̆%}
{#पङ्क्ति#} and {#पङ्क्ती#}¦ {%paṅktī̆%}

**Comment by Andhrabharati** [comment]
With the recent commit by Jim "handling" the shortlong tag, this issue could be closed now; isn't it @funderburkjim ?

**Comment by Andhrabharati** [comment]
Now that the shortlong entities got expanded as two variant forms, this issue could be closed now.
