### ISSUE TITLE
where to propose changes?

### ISSUE THREAD

**Issue by parjanya** [sanskrit-lexicon/csl-orig#7]
Hi all. I’ve been invited, long ago already, to help with you guys, but I never got to understand exactly where everything is being done, or should be done. So I’m guessing it’s here for now?

I’m working on SHS... I will present to you whatever I make as soon as it is presentable... and I have found some inconsistencies. I don’t know if I should pull the changes to this repository, so I’m writing a list here until I know better.

I’m putting the whole line in the hope it helps finding it in the file.

---

`{#adfzwapUrvva#}¦ mfn.({#-rvvaH-rvvA-rvvaM#}) Unseen previously, unseen till now. E. {#adfzwa,#}`

There is a missing space after `mfn.`

---

`{#aDaHkzipta (-ptaH-ptA-ptaM)#}¦ Precipitated, thrown down. E. {#aDas#} down, and {#kzipta#}`

This one doesn’t have the gender information, and this is according to the original which lacks it too. On my copy I changed it to the following:

`{#aDaHkzipta (-ptaH-ptA-ptaM)#}¦ mfn. Precipitated, thrown down. E. {#aDas#} down, and {#kzipta#}`

---

`{#aciradyuti#}¦ ({#-tiH#}) Lightning. E. {#a#} neg. {#cira#} long. and {#dyuti#} light.`

Missing gender again, M-W gives it as a feminine, and so on mine I put:

`{#aciradyuti#}¦ f. ({#-tiH#}) Lightning. E. {#a#} neg. {#cira#} long. and {#dyuti#} light.`

---

`{#ana#}¦ ({#-Ga#}) r. 2d. cl. ({#aniti#}) Also of 4th cl. {#(Na) (anyate)#} To breathe, to`

Should this  `({#-Ga#})` be really before r.? I haven’t seeing another example of this, nor do I know what to do with it. The original has the same.

---

`{#anuSAsitf (-tA-trI-tf)#}¦ Ruling, governing, commanding, directing, a ruler,`

the gender is missing, but clearly implied

---

`{#andola#}¦ ({#-ta#}) r. 10th cl. ({#andolayati#}) To agitate, to swing.`

What does this mean?

---

`{#anDa#}¦ ({#-ta#}) r. 10th cl. ({#anDayati#}) To be or become blind.`

idem

---

`{#x#}¦ aptote. 1. The divine nature. 2. The earth. 3. A mountain. ind. A`

as in the original. should this mean "ind.", indeclinable, avyayam?

---

`{#X#}¦ aptote. 1. A divine female. 2. The female nature. 3. A mother. m.`

likewise

--- 

`{#oja#}¦ ({#ta#}) r. 1st. cl. ({#ojati#}) 1. To live, to have the vital faculties and`

similiter

--- 

`{#KaRqakAvya#}¦ ({#-vyaM#}) n. A poem interspersed with prose. E. {#KaRqa,#} and {#kAvya#} a`

This is the only (?) case with the last akṣara of the nominative *before* the gender.

---

`{#KaleDAnI#}¦ ({#-nI#}) Tho post of a threshing floor, round which the oxen`

just a feminine? if so, why the akṣara? to mark it isn’t like śrīḥ?

---

`{#goDenu#}¦ ({#-nuH#}) A milch cow. E. {#go#} a cow, and {#Denu#} the same. {#savatsAyAM gavi .#}`

I’ve added an `f.` there.

`{#goDenu#}¦ f. ({#-nuH#}) A milch cow. E. {#go#} a cow, and {#Denu#} the same. {#savatsAyAM gavi .#}`

---

`{#cucu#}¦ imitative sound, (such as a child makes in sucking,) and {#ka#}`

`ind.` perhaps?

---

`{#QuQa (i) QuQi#}¦ Sautra root, ({#QuRQati#}) To search, to seek. {#BvA-para-saka-sew .#}`

That instead of `r.` something is quite irregular.

--- 

`{#Cfda#}¦ ({#u#} and {#ira#}) {#uCfdira#} r. 7th cl. ({#-CfRatti-CiMtte#}) 1. To shine 2. To vomit.`

irregular

---

{#tad#}¦ Relative or third personal pronoun. ({#saH sA tad#}) He, she, it, that

idam has `pron.` first.

---

{#tuqa (f) tuqf dviDAkaraRe (toqati)#}¦ also {#(i) tuqi#} r. 1st cl. {#nizpIqane (tuRqate)#} also

---
`{#dArGasatra(-traH-trI-traM)#}¦ Performing a long continued sacrifice, &c. E. {#dIrGasatra#}`

missing gender:

`{#dArGasatra(-traH-trI-traM)#}¦ mfn. Performing a long continued sacrifice, &c. E. {#dIrGasatra#}`

---

`{#durGoza#}¦ ({#-zaH-zA-zaM#}) Harsh-voiced, roaring, bellowing. m. ({#-zaH#}) 1. A bear.`

idem

`{#durGoza#}¦ mfn. ({#-zaH-zA-zaM#}) Harsh-voiced, roaring, bellowing. m. ({#-zaH#}) 1. A bear.`

---

`{#dvijihva#}¦ (mfn.) ({#-hvaH-hvA-hvaM#}) Double-tongued, (literally or figuratively.) m.`

why the parentheses?

---

`{#Darmapatra#}¦ ({#-traM#}) Glomerous fig tree, (Ficus glomerata) E. {#Darma#} sacrifice,`

missing gender

`{#Darmapatra#}¦ n. ({#-traM#}) Glomerous fig tree, (Ficus glomerata) E. {#Darma#} sacrifice,`

---

`{#pariBUzaRa#}¦ Peace obtained by cession of the revenue of a land.`

M-W gives it as a masculine.

---

`{#saptadvIpA#}¦ ({#-pA#}) An epithet of the earth.`

M-W gives as mfn., but here it’s only feminine...

---

`{#supratIka#}¦ ({#-kaH-kA-kaM#}) 1. Well-made, handsome. 2. Having a beautiful`

mfn.

---

Thanks :)

**Comment by gasyoun** [comment]
Namaste, Parjanya!

> I’m working on SHS

What exactly do you do with it? You use it for everyday reference work? 
First please tell more details about yourself. After I can see if I can be of any help to you.

**Comment by drdhaval2785** [comment]
@parjanya 
This is the exact place where you report errors.
You have done so.

**Comment by drdhaval2785** [comment]
@parjanya 
I would frame the suggestions as mentioned in https://github.com/sanskrit-lexicon/csl-orig/issues/8, so that we can refer to the cases and discuss it. Some changes may be incorporated and some may not, depending on the case.

**Comment by parjanya** [comment]
right now I’m parsing the entries, that’s why I found the inconsistencies. I teach Sanskrit, and I want to parse the whole thing in order to have the ‘etymology’ as the SHS gives it for each word, like *veda* "vid aff. ghañ" for instance, for my Pāṇinian studies, searching for the affixes for example, and all the rest... genders, meanings, root classes etc, for me to start creating a Portuguese dictionary eventually. Right now, however, I will be happy enough if I parse the whole file.

I would like for you guys to profit as much as possible from my tests, so I will keep sending this kind of report... or perhaps many small pull requests that you can decide to take or not. Ideally my parsing will be done from the raw file; if you don’t accept everything, it will be from `raw file → my tweakings → parsed dictionary`.
