### ISSUE TITLE
mw: 230551 sad

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#732]
date:	11/23/2021 22:49:36
dict:	mw
Lnum:	
hw:	sad
old:	adma-, antarikṣa-, apsu-sad 
new:	sádā Sanskrit markup missing
comm:

**Comment by funderburkjim** [comment]
Sanskrit markup added.

```
<L>230550<pc>1138,3<k1>sad<k2>sa/d<h>3<e>2
<hom>3.</hom> <s>sa/d</s> ¦ <lex>mfn.</lex> (mostly <ab>ifc.</ab>; for <hom>1.</hom> See 
<pcol>p. 1137, col. 1</pcol>) sitting or dwelling in (<ab>cf.</ab> <s>adma-</s>, <s>antarikza-</s>, 
<s>apsu-sad</s> &c.)<info lex="m:f:n"/>
<LEND>

<L>230551<pc>1138,3<k1>sad<k2>sa/d<e>2B
<s>sa/d</s> ¦ covering (the female); <s>sa/dA</s> = ‘ever’ in <ls>AV. iv, 4, 7</ls> 
<info n="rev" pc="1332,3"/>
<LEND>
```
The display:
![image](https://user-images.githubusercontent.com/6393033/146837597-de20aa62-5c37-4cfe-a677-b40b920bb476.png)

The main text as printed:
![image](https://user-images.githubusercontent.com/6393033/146837754-af6eff57-b302-4726-944e-66e2cd9be6a1.png)

The portion from additions/corrections p. 1332:
![image](https://user-images.githubusercontent.com/6393033/146837838-d3921c0a-63a1-4e57-8acd-7db85d55c85d.png)

Note that the display gives no clue that a revision has been applied.

**Comment by Andhrabharati** [comment]
I was telling about such incidences ealier; A&C corrections been implemented at few places, but without any markings.
