### ISSUE TITLE
VCP - Degree sign needed instead of anusvAra?

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#746]
This unusual data comes from https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=VCP&page=0991
```
(1/1) dfSyam 63 . atra rUpam 1 rASiM prakalpya
(1M/2) BAgAn SezAm SezAdapAsya aTavA BAgA-
(2M/9) pavAhaviDinA savarRite jAtam . (7/60)
(1M/4) anena 1 izwaguRite 63 dfzwe . Bakte jAtaM
(6M/10) dravyapramARam . 540 . idaM vilomasUtre-
RApi siDyati . aTa viSlezajAtyudAharaRam . “paYcAM-
```

**Comment by vvasuki** [comment]
> I would suggest something like the following. I am not sure. Hence asking for opinion of colleagues.
> 
> ```
> (1/1) dfSyam 63 . atra rUpam 1 rASiM prakalpya
> (1°/2) BAgAn SezAm SezAdapAsya aTavA BAgA-
> (2°/9) pavAhaviDinA savarRite jAtam . (7/60)
> (1°/4) anena 1 izwaguRite 63 dfzwe . Bakte jAtaM
> (6°/10) dravyapramARam . 540 . idaM vilomasUtre-
> RApi siDyati . aTa viSlezajAtyudAharaRam . “paYcAM-
> ```

Good proposal. anusvAra following a number makes no sense.

**Comment by Andhrabharati** [comment]
It is not an anusvara, as marked in CDSL text, nor is it a degree symbol, as proposed by Dhaval.

It is a special mark used in VCP to denote a multiplier.

In this context, I would like to remind about my earlier post, regarding another symbol having been used for denoting a negative number (in VCP).

There are more such symbols employed in the mathematical portions in VCP, taken from Bhaskaracharya's works (Lilavati or Goladhyaya).

**Comment by Andhrabharati** [comment]
A better option is not to digitise all those nyAsa portions as text, but to keep them as images and insert between (or besides) the running text.

**Comment by Andhrabharati** [comment]
For easy understanding of my above remark, posting the English tr. of the resp. verse from Lilavati, showing the multiplication mark (action) at resp. places-

![image](https://user-images.githubusercontent.com/75209130/154533684-9f8023e4-2769-41e8-865c-f2492b418392.png)
![image](https://user-images.githubusercontent.com/75209130/154533920-9e77cd5c-8579-4eae-9453-51f96c3b47b0.png)

**Comment by vvasuki** [comment]
> A better option is not to digitise all those nyAsa portions as text, but to keep them as images and insert between (or besides) the running text.

An even superior option is to just use modern understandable notation as shown in https://github.com/sanskrit-lexicon/csl-orig/issues/746#issuecomment-1043200617 .  As I mentioned in https://github.com/sanskrit-lexicon/csl-ldev/pull/3#issuecomment-1042960770 , it does not make sense to fanatically stick to the formatting and presentation from 100+ years ago. Historians can see the printed text. Users just want to grok what the author wanted to communicate.

**Comment by Andhrabharati** [comment]
For positive numbers, no marking ; but for negative numbers, this symbol is employed.

This is just same as the western/modern system, a negative number being marked by the minus sign.

**Comment by Andhrabharati** [comment]
For positive numbers, no marking ; but for negative numbers, this symbol is employed.

This is just same as the western/modern system, a negative number being marked by the minus sign.

As such this urdhvabindu is not a anusvara, but a combining dot to right (u+0358)!!

And, I feel this symbol should be marked thus, so that our ancient roots are not replaced by the modern/western equivalents.

**Comment by vvasuki** [comment]
> And, I feel this symbol should be marked thus, so that our ancient roots are not replaced by the modern/western equivalents.

१◌͘ will look like: 
![image](https://user-images.githubusercontent.com/2664797/154780884-30a2f4be-5b28-40da-bd98-c5552cf27b2f.png)
It will be a long time before you draft a unicode proposal, get it accepted, and then convince font makers to set it right.

Degree will look ok. It's perhaps better to use it instead in the meantime. 

In any case, if you want to retain it out of heritage pride, include modern equivalent notation in brackets.

**Comment by Andhrabharati** [comment]
Yes, I understand that unicode 'recognition' of a character takes lot of time and effort, and patience persuation.

For aesthetic looks, having a degree symbol is the simplest way. But doesn't that seem odd, when there are no angular quantities are involved?

**Comment by vvasuki** [comment]
> For aesthetic looks, having a degree symbol is the simplest way. But doesn't that seem odd, when there are no angular quantities involved?

Definitely odd. Someone (@Andhrabharati ?) should draft a proposal and fix this problem properly. (cc @jamadagni @sridatta1 @virtualvinodh who might be able to help)

> How about this-- १ꞏ?

Seems ok.

**Comment by vvasuki** [comment]
@Andhrabharati भोः-  भवत्परिचयं प्रेप्सामि। ९५९१२६८५०६ इत्यत्र सन्देशम् प्रेषयतु - टॆलिग्रामि वाट्साप्पि वा।

**Comment by Andhrabharati** [comment]
I saw your activities at githib, and posts at BVP, @vvasuki.

You definitely are a knowledgeable person; but too aggressive at times.

Unfortunately I don't talk much, nor like to go public. (You know 'us' st andhrabharati.com in a different context!!)

We can interact through mails, as we have some common thoughts and interests, if you like.

**Comment by vvasuki** [comment]
> Unfortunately I don't talk much, nor like to go public. (You know 'us' at andhrabharati.com in a different context!!)
> 
> We can interact through mails, as we have some common thoughts and interests, if you like.

एवम् अस्तु। विपत्रं तर्हि मे प्रेषय।

**Comment by gasyoun** [comment]
> You definitely are a knowledgeable person; but too aggressive at times.

It's the first time @Andhrabharati admits one can be aggressive in lexicography )) I like you both.

**Comment by Andhrabharati** [comment]
> > You definitely are a knowledgeable person; but too aggressive at times.
> 
> It's the first time @Andhrabharati admits one can be aggressive in lexicography )) I like you both.

I am not sure if Vasuki is much into lexicographical works.

My remark is a generic one, mostly about the way he puts his arguments

**Comment by Andhrabharati** [comment]
More often than not, VCP had used the black dot.

The circular figure resembling a degree is occassional, coming under the **all pervading inconstency** in its print. 

Incidentally, Taranatha's other (smaller) lexical work Sabdastomamahanidhi is almost conistent throughout. (And I am half-way through in making a digital text of it.)

**Comment by gasyoun** [comment]
> Sabdastomamahanidhi is almost conistent throughout. (And I am half-way through in making a digital text of it.)

Never even heard of it - of utmost interest when you finish it.

**Comment by vvasuki** [comment]
> Sabdastomamahanidhi is almost conistent throughout. (And I am half-way through in making a digital text of it.)

I'd very much appreciate it if you could notify me once it's done. @drdhaval2785 and I produce and heavily use dicts in stardict format in our various devices. https://github.com/indic-dict/ and https://sanskrit-coders.github.io/dictionaries/offline/Stardict/#how-to-install-and-use-dictionaries-on-your-device 

We cover dicts in many Indian languages including Telugu in that project. So, any dictionary we don't have which you can provide (preferably in babylon glossary format) will benefit users like us.

With apologies for the digression:

> > It's the first time @Andhrabharati admits one can be aggressive in lexicography )) I like you both.
> 
> I am not sure if Vasuki is much into lexicographical works.

Vasuki is my dad. I am Vishvas.

> 
> My remark is a generic one, mostly about the way he puts his arguments

:-D I'm nothing compared to Russians.

**Comment by Andhrabharati** [comment]
> Vasuki is my dad. I am Vishvas.

Sorry that I got misled by your id (vvasuki); now you made it clear for anyone (vAsukijaH)!!

**Comment by Andhrabharati** [comment]
> We cover dicts in many Indian languages

Do you have Kittel's dictionary?

DSAL has made their work public now; though still with few big errors uncorrected. (guess, you could take their text)

We had corrected its major portion at our end. (We don't share the works we takeup for hosting at andhrabharati.com; and the SSM work is not being done for that purpose, so could be shared.)

**Comment by vvasuki** [comment]
> > We cover dicts in many Indian languages
> 
> Do you have Kittel's dictionary?

yes

> 
> DSAL has made their work public now; though still with few big errors uncorrected. (guess, you could take their text)
> 

Got many of those.

> We had corrected its major portion at our end. 

Which ones did you correct? Can you share?

> (We don't share the works we takeup for hosting at andhrabharati.com; 

Sad but ok.

> and the SSM work is not being done for that purpose, so could be shared.)

Great!

**Comment by Andhrabharati** [comment]
> Which ones did you correct? Can you share?

pl. read my above post again, contextually.

(we did the work 3 years back itself)

**Comment by Andhrabharati** [comment]
> How about this-- १ꞏ?
> 
> Looks good & matches the context; but cannot be typed, only possible with copy&paste.
> 
> As this would be done very rarely, should be alright.

@vvasuki , @drdhaval2785 , @funderburkjim 

This character already has a place in unicode devanagari block!

It is the one next to devanagari abbr. Sign (u+0970); but this u+0971 character is not looking as prominent/clear as the one I had proposed above.

**Comment by vvasuki** [comment]
> It is the one next to devanagari abbr. Sign (u+0970); but this u+0971 character 

Then, it's best to use that. 

> is not looking as prominent/clear as the one I had proposed above (u+A78F).

That's a font/ display issue - future fonts may deal with it better and substitutions before display can be made in the meantime. Should not affect what code is used (u+0971) while encoding.

**Comment by funderburkjim** [comment]
change installed at Cologne.

**Comment by Andhrabharati** [comment]
@drdhaval2785 & @funderburkjim 

There are 80 more places where such condition (a number followed by anusvAra that needs this correction) is seen in the vcp.txt
