### ISSUE TITLE
AP90 etymology markup error

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#748]
`({#aMSaM lAti; lA-ka#})` should be `[{#aMSaM lAti; lA-ka#}]`
There may be similar errors at other places. 

ap90.txt

```
{#aMSala#}¦ {%<ab>a.</ab>%} ({#aMSaM lAti; lA-ka#}) {@1@} Having,
```

AP90 scanned image

![image](https://user-images.githubusercontent.com/5755132/155832314-73ad5752-70a2-4344-9b47-3b0a1ed1f466.png)

AP scanned image

![image](https://user-images.githubusercontent.com/5755132/155832341-7222aaff-bf2a-48df-a0a9-e6e13be4c3af.png)

**Comment by funderburkjim** [comment]
It might be useful to put these etymology sections within an xml tag.  We could provisionally use the 
`<etym>` tag here  (this tag currently used only in MW, although for a different purpose - related Indo-European words).

The reason for so doing would be to make it easier to identify such material for further analysis.

There is similar material in Wilson dictionary, and adding similar `<etym>` markup would also make that material more accessible and analyzable. 

If we add this tag,  then we should also consider the impact on displays  (for instance, we might initially decide to slightly change make_xml.py to ignore this tag for ap90, wil.

**Comment by Andhrabharati** [comment]
> There is similar material in Wilson dictionary, and adding similar `<etym>` markup would also make that material more accessible and analyzable.

This "kind of info" occurs **abundantly** in SKD and VAC, coming under 'grammatical derivation' of the words.

**Comment by drdhaval2785** [comment]
This issue is corrected via https://github.com/sanskrit-lexicon/csl-orig/commit/4b1d6eff7bf3b771dfe1f68e33d09ed982dd3ad0

**Comment by funderburkjim** [comment]
This is a print change for ap90 (using square brackets, as in ap90).

**Comment by funderburkjim** [comment]
correction installed at Cologne

**Comment by funderburkjim** [comment]
change installed at Cologne.
