### ISSUE TITLE
SHS - 1

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#8]
# Case 1

`{#adfzwapUrvva#}¦ mfn.({#-rvvaH-rvvA-rvvaM#}) Unseen previously, unseen till now. E. {#adfzwa,#}`

There is a missing space after `mfn.`

# Case 2

`{#aDaHkzipta (-ptaH-ptA-ptaM)#}¦ Precipitated, thrown down. E. {#aDas#} down, and {#kzipta#}`

This one doesn’t have the gender information, and this is according to the original which lacks it too. On my copy I changed it to the following:

# Case 3

`{#aDaHkzipta (-ptaH-ptA-ptaM)#}¦ mfn. Precipitated, thrown down. E. {#aDas#} down, and {#kzipta#}`

# Case 4

`{#aciradyuti#}¦ ({#-tiH#}) Lightning. E. {#a#} neg. {#cira#} long. and {#dyuti#} light.`

Missing gender again, M-W gives it as a feminine, and so on mine I put:

# Case 5

`{#aciradyuti#}¦ f. ({#-tiH#}) Lightning. E. {#a#} neg. {#cira#} long. and {#dyuti#} light.`

# Case 6

`{#ana#}¦ ({#-Ga#}) r. 2d. cl. ({#aniti#}) Also of 4th cl. {#(Na) (anyate)#} To breathe, to`

Should this  `({#-Ga#})` be really before r.? I haven’t seeing another example of this, nor do I know what to do with it. The original has the same.

# Case 7

`{#anuSAsitf (-tA-trI-tf)#}¦ Ruling, governing, commanding, directing, a ruler,`

the gender is missing, but clearly implied

# Case 8

`{#andola#}¦ ({#-ta#}) r. 10th cl. ({#andolayati#}) To agitate, to swing.`

What does this mean?

# Case 9

`{#anDa#}¦ ({#-ta#}) r. 10th cl. ({#anDayati#}) To be or become blind.`

idem

# Case 10

`{#x#}¦ aptote. 1. The divine nature. 2. The earth. 3. A mountain. ind. A`

as in the original. should this mean "ind.", indeclinable, avyayam?

# Case 11

`{#X#}¦ aptote. 1. A divine female. 2. The female nature. 3. A mother. m.`

likewise

# Case 12

`{#oja#}¦ ({#ta#}) r. 1st. cl. ({#ojati#}) 1. To live, to have the vital faculties and`

similiter

# Case 13

`{#KaRqakAvya#}¦ ({#-vyaM#}) n. A poem interspersed with prose. E. {#KaRqa,#} and {#kAvya#} a`

This is the only (?) case with the last akṣara of the nominative *before* the gender.

# Case 14

`{#KaleDAnI#}¦ ({#-nI#}) Tho post of a threshing floor, round which the oxen`

just a feminine? if so, why the akṣara? to mark it isn’t like śrīḥ?

# Case 15

`{#goDenu#}¦ ({#-nuH#}) A milch cow. E. {#go#} a cow, and {#Denu#} the same. {#savatsAyAM gavi .#}`

I’ve added an `f.` there.

`{#goDenu#}¦ f. ({#-nuH#}) A milch cow. E. {#go#} a cow, and {#Denu#} the same. {#savatsAyAM gavi .#}`

# Case 16

`{#cucu#}¦ imitative sound, (such as a child makes in sucking,) and {#ka#}`

`ind.` perhaps?

# Case 17

`{#QuQa (i) QuQi#}¦ Sautra root, ({#QuRQati#}) To search, to seek. {#BvA-para-saka-sew .#}`

That instead of `r.` something is quite irregular.

# Case 18

`{#Cfda#}¦ ({#u#} and {#ira#}) {#uCfdira#} r. 7th cl. ({#-CfRatti-CiMtte#}) 1. To shine 2. To vomit.`

irregular

# Case 19

{#tad#}¦ Relative or third personal pronoun. ({#saH sA tad#}) He, she, it, that

idam has `pron.` first.

# Case 20

{#tuqa (f) tuqf dviDAkaraRe (toqati)#}¦ also {#(i) tuqi#} r. 1st cl. {#nizpIqane (tuRqate)#} also

# Case 21

`{#dArGasatra(-traH-trI-traM)#}¦ Performing a long continued sacrifice, &c. E. {#dIrGasatra#}`

missing gender:

`{#dArGasatra(-traH-trI-traM)#}¦ mfn. Performing a long continued sacrifice, &c. E. {#dIrGasatra#}`

# Case 22

`{#durGoza#}¦ ({#-zaH-zA-zaM#}) Harsh-voiced, roaring, bellowing. m. ({#-zaH#}) 1. A bear.`

idem

`{#durGoza#}¦ mfn. ({#-zaH-zA-zaM#}) Harsh-voiced, roaring, bellowing. m. ({#-zaH#}) 1. A bear.`

# Case 23

`{#dvijihva#}¦ (mfn.) ({#-hvaH-hvA-hvaM#}) Double-tongued, (literally or figuratively.) m.`

why the parentheses?

# Case 24

`{#Darmapatra#}¦ ({#-traM#}) Glomerous fig tree, (Ficus glomerata) E. {#Darma#} sacrifice,`

missing gender

`{#Darmapatra#}¦ n. ({#-traM#}) Glomerous fig tree, (Ficus glomerata) E. {#Darma#} sacrifice,`

# Case 25

`{#pariBUzaRa#}¦ Peace obtained by cession of the revenue of a land.`

M-W gives it as a masculine.

# Case 26

`{#saptadvIpA#}¦ ({#-pA#}) An epithet of the earth.`

M-W gives as mfn., but here it’s only feminine...

# Case 27

`{#supratIka#}¦ ({#-kaH-kA-kaM#}) 1. Well-made, handsome. 2. Having a beautiful`

mfn.

**Comment by drdhaval2785** [comment]
# cases 2-5, 10, 11, 15, 16, 19, 21, 22, 24, 25, 26, 27

Not required to add details on our own. If the lexicographer has given it, we use it. Otherwise we leave it as it is.

**Comment by parjanya** [comment]
`<>to go, to rpeserve, &c. {#man#} Unadi affix, the radical being convert-`
→
`<>to go, to preserve, &c. {#man#} Unadi affix, the radical being convert-`

**Comment by parjanya** [comment]
`{#vaprAntara#}¦ 1nd. In or between banks, mounds, &c. E. {#vapra, antar#} within.`
→ 
`{#vaprAntar#}¦ Ind. In or between banks, mounds, &c. E. {#vapra, antar#} within.`

It’s indeclinable, but actually written 1nd. in the original, and the र for र् looks very much like a typographical error.

**Comment by drdhaval2785** [comment]
Good catches @parjanya

**Comment by parjanya** [comment]
`{#Rasa#}¦ r., 1st cl. ({#nasate (praRasate)#} 1. To be crooked, (literally or metaphorical-`
→
`{#Rasa#}¦ r., 1st cl. ({#nasate (praRasate)#} 1. To be crooked, (literally or metaphorical-`

the `.,` is in the original, but only here and in the `bil` does one see ` r.,`

**Comment by parjanya** [comment]
`{#pramATin#}¦ mfw. ({#TI-TinI-Ti#}) 1. Afflicting, inflicting pain or sorrow. 2.`
→
`{#pramATin#}¦ mfn. ({#TI-TinI-Ti#}) 1. Afflicting, inflicting pain or sorrow. 2.`

**Comment by parjanya** [comment]
`{#aBfSam#}¦ ing. A little, a few. E. {#a#} neg. {#BfSam#} much.`
→
`{#aBfSam#}¦ ind. A little, a few. E. {#a#} neg. {#BfSam#} much.`

**Comment by parjanya** [comment]
"{#asADya#}¦ nfn. ({#-DyaH-DyA-DyaM#}) 1. Not to be effected, not proper or able to be"
→
"{#asADya#}¦ mfn. ({#-DyaH-DyA-DyaM#}) 1. Not to be effected, not proper or able to be"

**Comment by parjanya** [comment]
"{#kozWaka#}¦ n, ({#-kaM#}) 1. A granary 2. A treasury. 3. A brick-trough for"
→
"{#kozWaka#}¦ n. ({#-kaM#}) 1. A granary 2. A treasury. 3. A brick-trough for"

**Comment by drdhaval2785** [comment]
@parjanya,

If you are doing something programmatically to find out errors, it would be nice if you can provide it in a txt file later

The format can be simple
```
Linenumber\told\tOldVersion
Linenumber\tnew\tNewVersion
```
e.g.
```
48902	old	{#kozWaka#}¦ n, ({#-kaM#}) 1. A granary 2. A treasury. 3. A brick-trough for
48902	new	{#kozWaka#}¦ n. ({#-kaM#}) 1. A granary 2. A treasury. 3. A brick-trough for
```

This way we can use your data directly for correction, rather than manually doing the corrections.

**Comment by parjanya** [comment]
ok! will compile like that from now on :)

**Comment by drdhaval2785** [comment]
Whether these SHS changes were ever incorporated? I am not sure. Maybe we will have to look into SHS digitization.
