### ISSUE TITLE
Space before punctuation marks (reg. PWG, pwk and pwkvn)

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/csl-orig#855]
Here is the summary of counts of the above in the CDSL files--

![image](https://user-images.githubusercontent.com/75209130/179705026-9f2331a8-e999-476e-b616-6d0a56eb3712.png)

Whatever is the logic behind having these spaces thus, they definitely look odd to the eye.

The recently done pwkvn is far better in this, as compared to the earlier PWG and pwk.

**Comment by gasyoun** [comment]
> Whatever is the logic behind having these spaces thus, they definitely look odd to the eye.

I believe some are not by accident. I'm no fan of them either. But some serve a purpose in Devanagari mode, not to glue together?

**Comment by Andhrabharati** [comment]
There, of course, are some ` .` and ` ..` within the devanagari strings {#...#} that indicate the daṇḍa and double-daṇḍa marks; but still a majority are outside the devanagari strings in PWG and pwk.

The counts stand thus-
Outside {#...#}:	PWG (30200), pwk (41), pwkvn (1)
Within {#...#}:	PWG (14052), pwk (4), pwkvn (8)
[of these single & double dots are-- PWG (4759, 9293), pwk (0,4) and pwkvn (3,5)]

The rest of the points have no relation to devanagari script or otherwise.

**Comment by Andhrabharati** [comment]
I've updated my versions of PWG, pwk and pwkvn correcting these "space" issues.
**[If,** and when, my (resolved) files are accepted for incorporating into CDSL, these and many other points  in my posts would have been attended appropriately.]

As otherwise, @funderburkjim seems not bothered about this (for over a year now!), closing this issue now.
