### ISSUE TITLE
Alternate headwords in SHS

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#87]
There are a total of 14 such entries. Mostly the siblings of `{#apAc#}¦ or {#apAYc#}`.

**Comment by drdhaval2785** [comment]
Earlier we had no facility to accomodate alternate headwords. With changes of meta-line, this should be a doable thing now. Right, @funderburkjim ?

**Comment by Andhrabharati** [comment]
Such occurrences are in almost all the dictionaries, which I had termed as grouped words.

These were "done" to some extent in MW99 before I joined here, and after my pointing out the same, @funderburkjim had acted upon resolving all (or most of) such MW99 entries.

This should ideally be "properly" rendered in all the works [variant forms, comma separated lists, lists with and/or (with or without comma separations included)], not to mention any individual work.

**Comment by drdhaval2785** [comment]
Not doing this for now
```
{#kada#}¦ or {#(i) kadi#}
```
