### ISSUE TITLE
SHS - semi indeclinables

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#88]
SHS has 11 entries where the lexicographer has not tagged it as `ind.`, but has chosen to write an explanation that `It is used as an indeclinable in the sense of.....`.

E.g.
```
<L>24997<pc>454-a<k1>pIqitama<k2>pIqitama
{#pIqitama#}¦ It is used as an indeclinable in the sense of “fast,” “closely.”
<LEND>
...
<L>26225<pc>475-a<k1>pracCannam<k2>pracCannam
{#pracCannam#}¦ It is used as an indeclinable in the sense of “Secretly,” “covertly.”
<LEND>
```
etc.

**Comment by gasyoun** [comment]
So you propose to insert `[ind.]`?

**Comment by drdhaval2785** [comment]
I am not sure what I propose to do. Just noted the peculiar situation.

**Comment by funderburkjim** [comment]
shs does not currently have genders marked.   

If we were to do so,  we could follow the MW model:  `<lex>m.</lex>`.

There is also, in mw,  a `<info lex="m">` markup, which in mw serves the purpose of presenting
the gender information in a normalized form.   
```
mw hw = pIqitam
<s>pIqitam</s> ¦ <lex>ind.</lex> closely, <ls>R.</ls><info lex="ind"/>
```
(note by the way that 'pIqitama'  (with ending 'a') is an unlikely spelling for an indeclineable, despite what SHS says.)

The `<info lex="...">` normalized form is useful in such cases as:
```
hw = kfzRa
<hom>1.</hom> <s>kfzRa/</s> ¦ <lex>mf(<s>A/</s>)n.</lex>
 black, dark, dark-blue (opposed to <s>Sveta/</s>, <s>Sukla/</s>, <s>ro/hita</s>, and 
<s>aruRa/</s>), <ls>RV.</ls>; <ls>AV.</ls> &c.
<info lex="m:f#A:n"/>
```
It is much easier to parse `<info lex="m:f#A:n"/>`  (which implies the feminine form of the adjective is 'kfzRA'),
than it is to parse `<lex>mf(<s>A/</s>)n.</lex>`.

**Comment by gasyoun** [comment]
> The other feature of the <info lex="ind"/> form is that we could add it in shs for cases like 'pracCannam' where the usual 'ind.' indication is absent, though clearly implied.

As it is already an attested model, I vote for it.

`<info lex="m:f#A:n"/>` is informative and we do not have to just note it here, but can have it in the file itself.

**Comment by Andhrabharati** [comment]
> 
> 
> I am not sure what I propose to do. Just noted the peculiar situation.

Just refer to your "response" in another thread (10 days earlier to this post), @drdhaval2785 !
https://github.com/sanskrit-lexicon/csl-orig/issues/8#issuecomment-565802734

**Comment by drdhaval2785** [comment]
We leave them alone.
