### ISSUE TITLE
mw:42763.2, kaTam

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#89]
date: 11/30/2019
dict: mw
Lnum: 42763.2
hw: kaTam
old:  with नु it is sometimes = किमु
new: with नु it is sometimes = किम्

I decided to leave this unchanged.
But would like a second opinion from @drdhaval2785 and @SergeA .

```
with nu it is sometimes = kimu, or kutas 
  (e.g. kathaṃ nu, how much more! na kathaṃ nu, how much less!)
 katham is often connected, like kim, with the particles cana, cid, and api, which give an 
indefinite sense to the interrogative
```
I first thought this was a print error, since there is no 'kimu' headword in MW.  But was
surprised to see that 'kimu' also occurs in the discussion of 'kaTam' in MW72.

Then I noticed there is a headword 'aTa-kimu' in mw.
And finally noticed that some dictionaries DO have 'kimu' as headword
(from [hwnorm1c.txt](https://github.com/sanskrit-lexicon/hwnorm1/blob/master/ejf/hwnorm1c/hwnorm1c.txt) : BOP,BUR,SHS,SKD,VCP,WIL,YAT

kimu in SKD: kim ca uca iti dvandvasamāsaḥ   ( What is 'uca' here?)
kimu in WIL: kimu ind. Either, or, whether, implying doubt or discrimination: see kim.
kimu in BUR: kimu kimu (sfx. u) pourquoi? cf. u.   
u in BUR: Dans le sanscrit brâhmanique, u s'ajoute aux mots atha, kim et na pour former 
               atho, kimu et no; voyez ces mots.       

The conclusion, then, is that MW did indeed intend 'kimu', and not 'kim'.

I'm still fuzzy on 
* whether MW's entry under kaTam would be different if he had used 'kim' instead of 'kimu'
* the difference in meaning between 'kimu' and 'kim'.  
   (simple sample sentences would be nice)

**Comment by gasyoun** [comment]
> (simple sample sentences would be nice)

http://www.sanskrit-linguistics.org/dcs/index.php?contents=fundstellen&IDWord=176865

http://www.sanskrit-linguistics.org/dcs/index.php?contents=fundstellen&IDWord=209495

**Comment by funderburkjim** [comment]
Those are nice lists --- how do you know IDWORD=176865  means kimu?

**Comment by funderburkjim** [comment]
@gasyoun    how do you know IDWORD=176865 means kimu?

**Comment by gasyoun** [comment]
> IDWORD=176865 means kimu?

Hardly I understand the question. There is only one kimu, the link is there. @SergeA can add?

**Comment by funderburkjim** [comment]
Your link gives examples of 'kimu'.  Great.   BUT  the link itself does not contain 'kimu'.

So I don't know how to generate such a request.    For instance, suppose I wanted to have 
sentences with 'agre'.   How would I do that?

**Comment by gasyoun** [comment]
> So I don't know how to generate such a request. For instance, suppose I wanted to have
sentences with 'agre'. How would I do that?

https://youtu.be/awzU-OPa-d4

**Comment by funderburkjim** [comment]
Excellent explanation!  Thank you. 👍
